// GENERATED by engine/ — do not edit. Run: cd engine && npm run build:dashboard

// src/types.ts
var ENGINE_VERSION = "1.0.0";
var EngineError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "EngineError";
  }
};

// src/dates.ts
var MS_PER_DAY = 864e5;
var MS_PER_HOUR = 36e5;
var DOW_NAMES = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday"
];
var DATE_RE = /^(\d{4})-(\d{2})-(\d{2})$/;
var DATETIME_RE = /^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})(?::(\d{2}))?/;
function isValidDate(s) {
  if (!DATE_RE.test(s)) return false;
  const [y, m, d] = s.split("-").map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d));
  return dt.getUTCFullYear() === y && dt.getUTCMonth() === m - 1 && dt.getUTCDate() === d;
}
function epochDay(date) {
  if (!DATE_RE.test(date)) throw new EngineError(`Invalid date: ${date}`);
  const [y, m, d] = date.split("-").map(Number);
  return Math.round(Date.UTC(y, m - 1, d) / MS_PER_DAY);
}
function fromEpochDay(n) {
  const dt = new Date(n * MS_PER_DAY);
  const y = dt.getUTCFullYear();
  const m = String(dt.getUTCMonth() + 1).padStart(2, "0");
  const d = String(dt.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}
function addDays(date, n) {
  return fromEpochDay(epochDay(date) + n);
}
function daysBetween(a, b) {
  return epochDay(b) - epochDay(a);
}
function dayOfWeek(date) {
  const [y, m, d] = date.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).getUTCDay();
}
function parseDateTime(s) {
  const m = DATETIME_RE.exec(s);
  if (!m) throw new EngineError(`Invalid datetime: ${s}`);
  return Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], m[6] ? +m[6] : 0);
}
function timeOfDayMinutes(s) {
  const m = DATETIME_RE.exec(s);
  if (!m) throw new EngineError(`Invalid datetime: ${s}`);
  return +m[4] * 60 + +m[5];
}
function clockToMinutes(s) {
  const m = /^(\d{1,2}):(\d{2})$/.exec(s);
  if (!m) throw new EngineError(`Invalid time-of-day: ${s}`);
  return +m[1] * 60 + +m[2];
}
function inRange(date, start, end) {
  return date >= start && date <= end;
}

// src/settings.ts
var KNOWN_KEYS = /* @__PURE__ */ new Set([
  "run_mode",
  "preserve_locked_assignments",
  "eligible_driver_status",
  "license_enforcement",
  "license_protection_days",
  "certification_enforcement",
  "pto_protection",
  "availability_enforcement",
  "availability_required",
  "max_days_enforcement",
  "max_days",
  "max_days_window",
  "target_days_per_week",
  "weekly_hour_cap_enforcement",
  "weekly_hour_cap",
  "weekly_hour_window",
  "pto_counts_toward_cap",
  "pto_default_hours",
  "min_rest_enforcement",
  "min_rest_hours",
  "woc_enforcement",
  "woc_max_consecutive_days",
  "same_day_multi_shift",
  "historical_pattern_protection",
  "history_window_weeks",
  "attendance_scheduling",
  "attendance_penalty",
  "attendance_weight",
  "performance_scheduling",
  "scheduling_method",
  "assignment_mode",
  "rotation_batch_size",
  "rotation_start_day",
  "preferred_availability_priority",
  "preferred_availability_required",
  "preferred_enhancement",
  "preferred_enhancement_contiguous",
  "preferred_enhancement_extra",
  "affinity_enhancement",
  "affinity_day_order",
  "fifth_day_fill",
  "fifth_day_override_availability",
  "consecutive_working_days"
]);
function dayOrder(value) {
  const def = [0, 1, 2, 3, 4, 5, 6];
  if (value === void 0) return def;
  if (!Array.isArray(value) || value.length !== 7) {
    throw new EngineError(
      `Setting "affinity_day_order" must be 7 weekday indices`
    );
  }
  const seen = /* @__PURE__ */ new Set();
  for (const v of value) {
    if (!Number.isInteger(v) || v < 0 || v > 6 || seen.has(v)) {
      throw new EngineError(
        `Setting "affinity_day_order" must be a permutation of 0-6`
      );
    }
    seen.add(v);
  }
  return [...value];
}
function bool(value, key, fallback) {
  if (value === void 0) return fallback;
  if (value === true || value === "on") return true;
  if (value === false || value === "off") return false;
  throw new EngineError(`Setting "${key}" must be on/off, got ${String(value)}`);
}
function oneOf(value, key, allowed, fallback) {
  if (value === void 0) return fallback;
  if (!allowed.includes(value)) {
    throw new EngineError(
      `Setting "${key}" must be one of ${allowed.join("|")}, got ${String(value)}`
    );
  }
  return value;
}
function num(value, key, fallback, min, max) {
  if (value === void 0) return fallback;
  if (typeof value !== "number" || Number.isNaN(value)) {
    throw new EngineError(`Setting "${key}" must be a number`);
  }
  if (value < min || value > max) {
    throw new EngineError(`Setting "${key}" out of range [${min}, ${max}]`);
  }
  return value;
}
function validateSettings(raw) {
  const r = raw ?? {};
  for (const key of Object.keys(r)) {
    if (!KNOWN_KEYS.has(key)) {
      throw new EngineError(`Unknown setting "${key}"`);
    }
  }
  const historyWeeks = r.history_window_weeks ?? 4;
  if (historyWeeks !== 4 && historyWeeks !== 6 && historyWeeks !== 8) {
    throw new EngineError(`Setting "history_window_weeks" must be 4, 6, or 8`);
  }
  return {
    run_mode: oneOf(
      r.run_mode,
      "run_mode",
      ["fill_empty_only", "rebuild_unlocked", "full_rebuild"],
      "fill_empty_only"
    ),
    preserve_locked_assignments: bool(
      r.preserve_locked_assignments,
      "preserve_locked_assignments",
      true
    ),
    eligible_driver_status: oneOf(
      r.eligible_driver_status,
      "eligible_driver_status",
      ["active_only", "active_and_onboarding"],
      "active_only"
    ),
    license_enforcement: bool(r.license_enforcement, "license_enforcement", true),
    license_protection_days: num(r.license_protection_days, "license_protection_days", 0, 0, 365),
    certification_enforcement: bool(
      r.certification_enforcement,
      "certification_enforcement",
      true
    ),
    pto_protection: bool(r.pto_protection, "pto_protection", true),
    availability_enforcement: bool(
      r.availability_enforcement,
      "availability_enforcement",
      false
    ),
    availability_required: bool(
      r.availability_required,
      "availability_required",
      false
    ),
    max_days_enforcement: bool(r.max_days_enforcement, "max_days_enforcement", true),
    max_days: num(r.max_days, "max_days", 6, 0, 7),
    target_days_per_week: num(r.target_days_per_week, "target_days_per_week", 4, 0, 7),
    max_days_window: oneOf(
      r.max_days_window,
      "max_days_window",
      ["schedule_week", "rolling_7_days", "pay_period"],
      "schedule_week"
    ),
    weekly_hour_cap_enforcement: bool(
      r.weekly_hour_cap_enforcement,
      "weekly_hour_cap_enforcement",
      true
    ),
    weekly_hour_cap: num(r.weekly_hour_cap, "weekly_hour_cap", 50, 0, 168),
    weekly_hour_window: oneOf(
      r.weekly_hour_window,
      "weekly_hour_window",
      ["schedule_week", "rolling_7_days", "pay_period"],
      "schedule_week"
    ),
    pto_counts_toward_cap: bool(
      r.pto_counts_toward_cap,
      "pto_counts_toward_cap",
      true
    ),
    pto_default_hours: num(r.pto_default_hours, "pto_default_hours", 10, 0, 24),
    min_rest_enforcement: bool(r.min_rest_enforcement, "min_rest_enforcement", true),
    min_rest_hours: num(r.min_rest_hours, "min_rest_hours", 10, 0, 48),
    woc_enforcement: bool(r.woc_enforcement, "woc_enforcement", true),
    woc_max_consecutive_days: num(
      r.woc_max_consecutive_days,
      "woc_max_consecutive_days",
      6,
      1,
      7
    ),
    same_day_multi_shift: oneOf(
      r.same_day_multi_shift,
      "same_day_multi_shift",
      ["block", "allow"],
      "block"
    ),
    historical_pattern_protection: oneOf(
      r.historical_pattern_protection,
      "historical_pattern_protection",
      ["off", "low", "medium", "high"],
      "medium"
    ),
    history_window_weeks: historyWeeks,
    attendance_scheduling: bool(
      r.attendance_scheduling,
      "attendance_scheduling",
      true
    ),
    attendance_penalty: bool(r.attendance_penalty, "attendance_penalty", false),
    attendance_weight: oneOf(
      r.attendance_weight,
      "attendance_weight",
      ["low", "medium", "high"],
      "medium"
    ),
    performance_scheduling: bool(
      r.performance_scheduling,
      "performance_scheduling",
      false
    ),
    scheduling_method: oneOf(
      r.scheduling_method,
      "scheduling_method",
      [
        "fair_rotation",
        "seniority",
        "full_time_priority",
        "availability_first",
        "alphabetical",
        "attendance_priority",
        "random"
      ],
      "fair_rotation"
    ),
    assignment_mode: oneOf(
      r.assignment_mode,
      "assignment_mode",
      ["sequential_fill", "rotational_fill"],
      "rotational_fill"
    ),
    rotation_batch_size: num(r.rotation_batch_size, "rotation_batch_size", 1, 1, 4),
    rotation_start_day: num(r.rotation_start_day, "rotation_start_day", 0, 0, 6),
    preferred_availability_priority: bool(
      r.preferred_availability_priority,
      "preferred_availability_priority",
      true
    ),
    preferred_availability_required: bool(
      r.preferred_availability_required,
      "preferred_availability_required",
      false
    ),
    preferred_enhancement: bool(
      r.preferred_enhancement,
      "preferred_enhancement",
      false
    ),
    preferred_enhancement_contiguous: bool(
      r.preferred_enhancement_contiguous,
      "preferred_enhancement_contiguous",
      true
    ),
    preferred_enhancement_extra: bool(
      r.preferred_enhancement_extra,
      "preferred_enhancement_extra",
      false
    ),
    affinity_enhancement: bool(
      r.affinity_enhancement,
      "affinity_enhancement",
      false
    ),
    affinity_day_order: dayOrder(r.affinity_day_order),
    fifth_day_fill: bool(r.fifth_day_fill, "fifth_day_fill", false),
    fifth_day_override_availability: bool(
      r.fifth_day_override_availability,
      "fifth_day_override_availability",
      false
    ),
    consecutive_working_days: bool(
      r.consecutive_working_days,
      "consecutive_working_days",
      true
    )
  };
}

// src/normalize.ts
function snake(s) {
  return s.trim().toLowerCase().replace(/[\s-]+/g, "_");
}
function normalizeRouteType(raw) {
  const s = snake(String(raw));
  switch (s) {
    case "standard":
    case "std":
      return "standard";
    case "step_van":
    case "stepvan":
      return "step_van";
    case "xl":
    case "extra_large":
    case "extralarge":
      return "xl";
    case "edv":
      return "edv";
    default:
      throw new EngineError(`Unknown route_type: ${raw}`);
  }
}
function normalizeEmployment(raw) {
  const s = snake(String(raw));
  if (s === "full_time" || s === "fulltime" || s === "ft") return "full_time";
  if (s === "part_time" || s === "parttime" || s === "pt") return "part_time";
  throw new EngineError(`Unknown employment_type: ${raw}`);
}
function normalizeStatus(raw) {
  const s = snake(String(raw));
  if (s === "active" || s === "onboarding" || s === "inactive" || s === "suspended" || s === "terminated") {
    return s;
  }
  throw new EngineError(`Unknown driver status: ${raw}`);
}
function require2(value, field, where) {
  if (value === void 0 || value === null || value === "") {
    throw new EngineError(`Missing required field "${field}" in ${where}`);
  }
}
function validateAvailability(av, who) {
  if (av === void 0 || av === null) return null;
  const out = {};
  for (const key of Object.keys(av).sort()) {
    const dow = Number(key);
    if (!Number.isInteger(dow) || dow < 0 || dow > 6) {
      throw new EngineError(`Invalid availability weekday "${key}" for ${who}`);
    }
    const windows = av[key] ?? [];
    for (const w of windows) {
      if (typeof w.start !== "string" || typeof w.end !== "string") {
        throw new EngineError(`Invalid availability window for ${who}`);
      }
    }
    out[String(dow)] = windows;
  }
  return out;
}
function normalizeShift(raw) {
  const where = `shift ${raw.shift_id ?? "(no id)"}`;
  require2(raw.shift_id, "shift_id", where);
  require2(raw.date, "date", where);
  require2(raw.start_time, "start_time", where);
  require2(raw.route_type, "route_type", where);
  if (!isValidDate(raw.date)) {
    throw new EngineError(`Invalid date "${raw.date}" in ${where}`);
  }
  const duration = raw.duration_hours === void 0 || raw.duration_hours === null ? 10 : raw.duration_hours;
  if (typeof duration !== "number" || !(duration > 0)) {
    throw new EngineError(`Invalid duration_hours in ${where}`);
  }
  const startMs = parseDateTime(raw.start_time);
  const endMs = raw.end_time !== void 0 && raw.end_time !== null ? parseDateTime(raw.end_time) : startMs + duration * 36e5;
  if (endMs <= startMs) {
    throw new EngineError(`end_time not after start_time in ${where}`);
  }
  const startMin = timeOfDayMinutes(raw.start_time);
  const endMin = startMin + Math.round((endMs - startMs) / 6e4);
  return {
    shift_id: String(raw.shift_id),
    date: raw.date,
    dow: dayOfWeek(raw.date),
    start_ms: startMs,
    end_ms: endMs,
    duration_hours: duration,
    start_min: startMin,
    end_min: endMin,
    route_type: normalizeRouteType(raw.route_type),
    service_type: raw.service_type ? snake(raw.service_type) : null,
    wave: raw.wave ?? null,
    is_locked: raw.is_locked === true,
    override_reason: raw.override_reason ?? null,
    override_ack_by: raw.override_ack_by ?? null,
    original_assigned_driver_id: raw.assigned_driver_id ?? null
  };
}
function normalizeDriver(raw) {
  const where = `driver ${raw.driver_id ?? "(no id)"}`;
  require2(raw.driver_id, "driver_id", where);
  require2(raw.first_name, "first_name", where);
  require2(raw.last_name, "last_name", where);
  require2(raw.status, "status", where);
  require2(raw.employment_type, "employment_type", where);
  require2(raw.hire_date, "hire_date", where);
  if (!isValidDate(raw.hire_date)) {
    throw new EngineError(`Invalid hire_date "${raw.hire_date}" in ${where}`);
  }
  if (raw.license_expiration_date != null && !isValidDate(raw.license_expiration_date)) {
    throw new EngineError(`Invalid license_expiration_date in ${where}`);
  }
  const ptoDates = /* @__PURE__ */ new Set();
  const ptoHours = /* @__PURE__ */ new Map();
  for (const rec of raw.pto_records ?? []) {
    if (!isValidDate(rec.date)) {
      throw new EngineError(`Invalid PTO date "${rec.date}" in ${where}`);
    }
    ptoDates.add(rec.date);
    if (rec.hours !== void 0 && rec.hours !== null) {
      if (typeof rec.hours !== "number" || rec.hours < 0) {
        throw new EngineError(`Invalid PTO hours in ${where}`);
      }
      ptoHours.set(rec.date, rec.hours);
    }
  }
  let affinity = null;
  if (raw.weekday_affinity !== void 0 && raw.weekday_affinity !== null) {
    if (!Array.isArray(raw.weekday_affinity) || raw.weekday_affinity.length !== 7) {
      throw new EngineError(`Invalid weekday_affinity in ${where}`);
    }
    affinity = raw.weekday_affinity.map((p) => {
      const n = Number(p);
      if (Number.isNaN(n) || n < 0 || n > 100) {
        throw new EngineError(`Invalid weekday_affinity value in ${where}`);
      }
      return n;
    });
  }
  let score = null;
  if (raw.attendance_score !== void 0 && raw.attendance_score !== null) {
    if (typeof raw.attendance_score !== "number" || raw.attendance_score < 0 || raw.attendance_score > 100) {
      throw new EngineError(`Invalid attendance_score in ${where}`);
    }
    score = raw.attendance_score;
  }
  return {
    driver_id: String(raw.driver_id),
    first_name: raw.first_name,
    last_name: raw.last_name,
    status: normalizeStatus(raw.status),
    employment_type: normalizeEmployment(raw.employment_type),
    hire_date: raw.hire_date,
    license_expiration_date: raw.license_expiration_date ?? null,
    dot_certified: raw.dot_certified === true,
    xl_certified: raw.xl_certified === true,
    edv_certified: raw.edv_certified === true,
    saved_availability: validateAvailability(raw.saved_availability, where),
    preferred_availability: validateAvailability(
      raw.preferred_availability,
      where
    ),
    pto_dates: ptoDates,
    pto_hours: ptoHours,
    attendance_score: score,
    attendance_events: raw.attendance_events ?? [],
    attendance_final: raw.attendance_final === true,
    weekday_affinity: affinity,
    fifth_day_ok: raw.fifth_day_ok === true,
    sort_key: `${raw.last_name}\0${raw.first_name}`.toLowerCase()
  };
}

// src/adhoc.ts
var EMPTY = Object.freeze({
  excludeFromDay: /* @__PURE__ */ new Map(),
  blackouts: /* @__PURE__ */ new Map(),
  pairForbidden: /* @__PURE__ */ new Map(),
  maxDaysOverride: /* @__PURE__ */ new Map()
});
function indexAdHoc(constraints) {
  if (!constraints || constraints.length === 0) return EMPTY;
  const idx = {
    excludeFromDay: /* @__PURE__ */ new Map(),
    blackouts: /* @__PURE__ */ new Map(),
    pairForbidden: /* @__PURE__ */ new Map(),
    maxDaysOverride: /* @__PURE__ */ new Map()
  };
  for (const c of constraints) {
    if (!c || c.hardness !== "hard") continue;
    const p = c.payload ?? {};
    switch (c.kind) {
      case "driver_exclude_from_day": {
        const did = p.driver_id;
        const dow = p.dow;
        if (typeof did !== "string" || typeof dow !== "number") break;
        if (!Number.isInteger(dow) || dow < 0 || dow > 6) break;
        let set = idx.excludeFromDay.get(did);
        if (!set) {
          set = /* @__PURE__ */ new Set();
          idx.excludeFromDay.set(did, set);
        }
        set.add(dow);
        break;
      }
      case "date_blackout_driver": {
        const did = p.driver_id;
        const from = p.date_from;
        const to = p.date_to;
        if (typeof did !== "string") break;
        if (typeof from !== "string" || !isValidDate(from)) break;
        if (typeof to !== "string" || !isValidDate(to)) break;
        if (to < from) break;
        let arr = idx.blackouts.get(did);
        if (!arr) {
          arr = [];
          idx.blackouts.set(did, arr);
        }
        arr.push([from, to]);
        break;
      }
      case "driver_pair_forbidden": {
        const a = p.driver_a;
        const b = p.driver_b;
        if (typeof a !== "string" || typeof b !== "string" || a === b) break;
        let sa = idx.pairForbidden.get(a);
        if (!sa) {
          sa = /* @__PURE__ */ new Set();
          idx.pairForbidden.set(a, sa);
        }
        sa.add(b);
        let sb = idx.pairForbidden.get(b);
        if (!sb) {
          sb = /* @__PURE__ */ new Set();
          idx.pairForbidden.set(b, sb);
        }
        sb.add(a);
        break;
      }
      case "driver_max_days_override": {
        const did = p.driver_id;
        const cap = p.max_days;
        if (typeof did !== "string" || typeof cap !== "number") break;
        if (!Number.isFinite(cap) || cap < 0) break;
        const intCap = Math.floor(cap);
        const prev = idx.maxDaysOverride.get(did);
        if (prev === void 0 || intCap < prev) {
          idx.maxDaysOverride.set(did, intCap);
        }
        break;
      }
      // driver_lock_to_day is handled by step1_5_locks, not here.
      default:
        break;
    }
  }
  return idx;
}
function inBlackoutRange(iso, ranges) {
  if (!ranges) return false;
  for (const [from, to] of ranges) {
    if (iso >= from && iso <= to) return true;
  }
  return false;
}

// src/runtime.ts
function windowRange(type, shift, ctx) {
  if (type === "schedule_week") return ctx.scheduleWeek;
  if (type === "rolling_7_days") return [addDays(shift.date, -6), shift.date];
  return ctx.payPeriod;
}
function assignedDates(state) {
  const set = /* @__PURE__ */ new Set();
  for (const a of state.assigned) set.add(a.date);
  return set;
}
function uniqueDatesInWindow(state, range) {
  const set = /* @__PURE__ */ new Set();
  for (const a of state.assigned) {
    if (inRange(a.date, range[0], range[1])) set.add(a.date);
  }
  return set;
}
function workHoursInWindow(state, range) {
  let total = 0;
  for (const a of state.assigned) {
    if (inRange(a.date, range[0], range[1])) total += a.duration_hours;
  }
  return total;
}
function ptoHoursInWindow(driver, range, settings) {
  let total = 0;
  for (const date of driver.pto_dates) {
    if (!inRange(date, range[0], range[1])) continue;
    total += driver.pto_hours.get(date) ?? settings.pto_default_hours;
  }
  return total;
}
function fitsAvailability(av, shift) {
  const windows = av[String(shift.dow)];
  if (windows === void 0 || windows.length === 0) return false;
  for (const w of windows) {
    const start = clockToMinutes(w.start);
    const end = clockToMinutes(w.end);
    if (start <= shift.start_min && end >= shift.end_min) return true;
  }
  return false;
}
function isDotRoute(shift) {
  return shift.route_type === "step_van" || shift.route_type === "xl";
}
function compareSeniority(a, b) {
  if (a.hire_date !== b.hire_date) return a.hire_date < b.hire_date ? -1 : 1;
  if (a.sort_key !== b.sort_key) return a.sort_key < b.sort_key ? -1 : 1;
  return a.driver_id < b.driver_id ? -1 : a.driver_id > b.driver_id ? 1 : 0;
}

// src/hash.ts
function canonicalize(value) {
  if (value === void 0) return "null";
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value) ?? "null";
  }
  if (Array.isArray(value)) {
    return `[${value.map(canonicalize).join(",")}]`;
  }
  const obj = value;
  const keys = Object.keys(obj).filter((k) => obj[k] !== void 0).sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalize(obj[k])}`).join(",")}}`;
}
var K = new Uint32Array([
  1116352408,
  1899447441,
  3049323471,
  3921009573,
  961987163,
  1508970993,
  2453635748,
  2870763221,
  3624381080,
  310598401,
  607225278,
  1426881987,
  1925078388,
  2162078206,
  2614888103,
  3248222580,
  3835390401,
  4022224774,
  264347078,
  604807628,
  770255983,
  1249150122,
  1555081692,
  1996064986,
  2554220882,
  2821834349,
  2952996808,
  3210313671,
  3336571891,
  3584528711,
  113926993,
  338241895,
  666307205,
  773529912,
  1294757372,
  1396182291,
  1695183700,
  1986661051,
  2177026350,
  2456956037,
  2730485921,
  2820302411,
  3259730800,
  3345764771,
  3516065817,
  3600352804,
  4094571909,
  275423344,
  430227734,
  506948616,
  659060556,
  883997877,
  958139571,
  1322822218,
  1537002063,
  1747873779,
  1955562222,
  2024104815,
  2227730452,
  2361852424,
  2428436474,
  2756734187,
  3204031479,
  3329325298
]);
function rotr(x, n) {
  return x >>> n | x << 32 - n;
}
function sha256Hex(input) {
  const bytes = new TextEncoder().encode(input);
  const total = (bytes.length + 8 >> 6) * 64 + 64;
  const buf = new Uint8Array(total);
  buf.set(bytes);
  buf[bytes.length] = 128;
  const dv = new DataView(buf.buffer);
  const bitLen = bytes.length * 8;
  dv.setUint32(total - 4, bitLen >>> 0, false);
  dv.setUint32(total - 8, Math.floor(bitLen / 4294967296), false);
  let h0 = 1779033703;
  let h1 = 3144134277;
  let h2 = 1013904242;
  let h3 = 2773480762;
  let h4 = 1359893119;
  let h5 = 2600822924;
  let h6 = 528734635;
  let h7 = 1541459225;
  const w = new Uint32Array(64);
  for (let off = 0; off < total; off += 64) {
    for (let i = 0; i < 16; i++) w[i] = dv.getUint32(off + i * 4, false);
    for (let i = 16; i < 64; i++) {
      const a2 = w[i - 15];
      const b2 = w[i - 2];
      const s0 = rotr(a2, 7) ^ rotr(a2, 18) ^ a2 >>> 3;
      const s1 = rotr(b2, 17) ^ rotr(b2, 19) ^ b2 >>> 10;
      w[i] = w[i - 16] + s0 + w[i - 7] + s1 | 0;
    }
    let a = h0;
    let b = h1;
    let c = h2;
    let d = h3;
    let e = h4;
    let f = h5;
    let g = h6;
    let h = h7;
    for (let i = 0; i < 64; i++) {
      const s1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = e & f ^ ~e & g;
      const t1 = h + s1 + ch + K[i] + w[i] | 0;
      const s0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = a & b ^ a & c ^ b & c;
      const t2 = s0 + maj | 0;
      h = g;
      g = f;
      f = e;
      e = d + t1 | 0;
      d = c;
      c = b;
      b = a;
      a = t1 + t2 | 0;
    }
    h0 = h0 + a | 0;
    h1 = h1 + b | 0;
    h2 = h2 + c | 0;
    h3 = h3 + d | 0;
    h4 = h4 + e | 0;
    h5 = h5 + f | 0;
    h6 = h6 + g | 0;
    h7 = h7 + h | 0;
  }
  return [h0, h1, h2, h3, h4, h5, h6, h7].map((x) => (x >>> 0).toString(16).padStart(8, "0")).join("");
}
function inputsHash(input) {
  return `sha256:${sha256Hex(canonicalize(input))}`;
}

// src/steps/step1_prepare.ts
function prepareSchedule(ctx) {
  const mode = ctx.settings.run_mode;
  const preserveLocked = ctx.settings.preserve_locked_assignments;
  return ctx.shifts.map((shift) => {
    const orig = shift.original_assigned_driver_id;
    const locked = shift.is_locked;
    let assignedDriverId = null;
    let source = null;
    if (orig !== null && orig !== "") {
      if (mode === "fill_empty_only") {
        assignedDriverId = orig;
        source = locked ? "locked" : "preserved";
      } else if (mode === "rebuild_unlocked") {
        if (locked) {
          assignedDriverId = orig;
          source = "locked";
        }
      } else {
        if (locked && preserveLocked) {
          assignedDriverId = orig;
          source = "locked";
        }
      }
    }
    const isBlackout = ctx.blackout.has(shift.date);
    let open = assignedDriverId === null;
    let closed = false;
    if (isBlackout) {
      open = false;
      if (assignedDriverId === null) closed = true;
    }
    return { shift, assignedDriverId, source, open, closed };
  });
}

// src/rules/r011_blackout.ts
function checkBlackout(shift, blackout) {
  if (blackout.has(shift.date)) {
    return { rule: "R011", message: `${shift.date} is a DSP blackout date` };
  }
  return null;
}

// src/rules/r002_status.ts
function checkStatus(driver, settings) {
  if (driver.status === "active") return null;
  if (driver.status === "onboarding" && settings.eligible_driver_status === "active_and_onboarding") {
    return null;
  }
  return {
    rule: "R002",
    message: `Driver status is ${driver.status}, not eligible for auto-fill`
  };
}

// src/rules/r003_license.ts
function checkLicense(shift, driver, settings) {
  if (!settings.license_enforcement) return null;
  if (driver.license_expiration_date === null) {
    return { rule: "R003", message: "License expiration date missing" };
  }
  const daysToExpiry = daysBetween(shift.date, driver.license_expiration_date);
  if (daysToExpiry < 0) {
    return {
      rule: "R003",
      message: `License expired ${driver.license_expiration_date}`
    };
  }
  const window = settings.license_protection_days;
  if (window > 0 && daysToExpiry <= window) {
    return {
      rule: "R003",
      message: `License expires ${driver.license_expiration_date} \u2014 within the ${window}-day protection window`
    };
  }
  return null;
}

// src/rules/r004_certification.ts
function checkCertification(shift, driver, settings) {
  if (!settings.certification_enforcement) return null;
  if (shift.route_type === "step_van" && !driver.dot_certified) {
    return {
      rule: "R004",
      message: "Missing DOT certification for step_van route"
    };
  }
  if (shift.route_type === "xl" && !driver.xl_certified) {
    return { rule: "R004", message: "Missing XL certification" };
  }
  if (shift.route_type === "edv" && !driver.edv_certified) {
    return { rule: "R004", message: "Missing EDV certification" };
  }
  return null;
}

// src/rules/r005_pto.ts
function checkPto(shift, driver, settings) {
  if (!settings.pto_protection) return null;
  if (driver.pto_dates.has(shift.date)) {
    return { rule: "R005", message: `Approved PTO on ${shift.date}` };
  }
  return null;
}

// src/rules/r006_availability.ts
function checkAvailability(shift, driver, settings) {
  if (!settings.availability_enforcement) return null;
  if (driver.saved_availability === null) {
    if (settings.availability_required) {
      return { rule: "R006", message: "No availability on file" };
    }
    return null;
  }
  if (fitsAvailability(driver.saved_availability, shift)) return null;
  return {
    rule: "R006",
    message: `Outside saved availability for ${DOW_NAMES[shift.dow]}`
  };
}

// src/rules/r010_same_day.ts
function checkSameDay(shift, state, settings) {
  if (settings.same_day_multi_shift === "allow") return null;
  for (const a of state.assigned) {
    if (a.shift_id === shift.shift_id) continue;
    if (a.date === shift.date) {
      return {
        rule: "R010",
        message: `Already assigned a shift on ${shift.date}`
      };
    }
  }
  return null;
}

// src/rules/r007_max_days.ts
function checkMaxDays(shift, state, ctx) {
  if (!ctx.settings.max_days_enforcement) return null;
  const range = windowRange(ctx.settings.max_days_window, shift, ctx);
  if (!inRange(shift.date, range[0], range[1])) return null;
  const dates = uniqueDatesInWindow(state, range);
  dates.add(shift.date);
  const override = ctx.adHoc.maxDaysOverride.get(state.driver_id);
  const cap = override !== void 0 ? Math.min(ctx.settings.max_days, override) : ctx.settings.max_days;
  if (dates.size > cap) {
    const note = override !== void 0 && override === cap ? ` (per-driver override)` : "";
    return {
      rule: "R007",
      message: `Would exceed max ${cap} days in ${ctx.settings.max_days_window}${note}`
    };
  }
  return null;
}

// src/rules/r008_weekly_cap.ts
var LUNCH_HOURS = 0.5;
function checkWeeklyCap(shift, driver, state, ctx) {
  const s = ctx.settings;
  if (!s.weekly_hour_cap_enforcement) return null;
  const range = windowRange(s.weekly_hour_window, shift, ctx);
  if (!inRange(shift.date, range[0], range[1])) return null;
  const work = workHoursInWindow(state, range);
  const shiftsInWindow = state.assigned.filter(
    (a) => inRange(a.date, range[0], range[1])
  ).length;
  const pto = s.pto_counts_toward_cap ? ptoHoursInWindow(driver, range, s) : 0;
  const netWork = Math.max(0, work - shiftsInWindow * LUNCH_HOURS);
  const netShift = Math.max(0, shift.duration_hours - LUNCH_HOURS);
  const projected = netWork + pto + netShift;
  if (projected > s.weekly_hour_cap) {
    return {
      rule: "R008",
      message: `Would reach ${Math.round(projected * 10) / 10}h on the clock, over ${s.weekly_hour_cap}h weekly cap`
    };
  }
  return null;
}

// src/rules/r009_min_rest.ts
function checkMinRest(shift, state, settings) {
  if (!settings.min_rest_enforcement) return null;
  const minMs = settings.min_rest_hours * MS_PER_HOUR;
  for (const a of state.assigned) {
    if (a.shift_id === shift.shift_id) continue;
    let gap;
    if (a.end_ms <= shift.start_ms) {
      gap = shift.start_ms - a.end_ms;
    } else if (shift.end_ms <= a.start_ms) {
      gap = a.start_ms - shift.end_ms;
    } else {
      gap = -1;
    }
    if (gap < minMs) {
      return {
        rule: "R009",
        message: `Less than ${settings.min_rest_hours}h rest from shift ${a.shift_id}`
      };
    }
  }
  return null;
}

// src/rules/r019_woc.ts
function checkWoc(shift, state, settings) {
  if (!settings.woc_enforcement) return null;
  const maxRun = settings.woc_max_consecutive_days;
  const dates = assignedDates(state);
  dates.add(shift.date);
  let run = 1;
  let cursor = addDays(shift.date, -1);
  while (dates.has(cursor)) {
    run += 1;
    cursor = addDays(cursor, -1);
  }
  cursor = addDays(shift.date, 1);
  while (dates.has(cursor)) {
    run += 1;
    cursor = addDays(cursor, 1);
  }
  if (run > maxRun) {
    return {
      rule: "R019",
      message: `WOC: would be consecutive working day #${run} (max ${maxRun})`
    };
  }
  return null;
}

// src/rules/r017_preferred.ts
function inPreferredWindow(shift, driver) {
  if (driver.preferred_availability === null) return false;
  return fitsAvailability(driver.preferred_availability, shift);
}
function preferredPoints(shift, driver, settings) {
  if (!settings.preferred_availability_priority) return 0;
  return inPreferredWindow(shift, driver) ? 10 : 0;
}

// src/rules/r020_preferred_required.ts
function checkPreferredRequired(shift, driver, settings) {
  if (!settings.preferred_availability_required) return null;
  if (driver.preferred_availability === null) {
    return { rule: "R020", message: "No preferred availability on file" };
  }
  if (inPreferredWindow(shift, driver)) return null;
  return {
    rule: "R020",
    message: `${DOW_NAMES[shift.dow]} is not a preferred day`
  };
}

// src/rules/r021_adhoc.ts
function checkAdHocExcludeFromDay(shift, driver, ctx) {
  const dows = ctx.adHoc.excludeFromDay.get(driver.driver_id);
  if (!dows || !dows.has(shift.dow)) return null;
  return {
    rule: "R021",
    message: `Ad-hoc: driver excluded from ${DOW_NAMES[shift.dow]}`
  };
}
function checkAdHocBlackout(shift, driver, ctx) {
  const ranges = ctx.adHoc.blackouts.get(driver.driver_id);
  if (!inBlackoutRange(shift.date, ranges)) return null;
  return {
    rule: "R021",
    message: `Ad-hoc: driver on blackout range covering ${shift.date}`
  };
}
function checkAdHocPairForbidden(shift, driver, ctx) {
  const partners = ctx.adHoc.pairForbidden.get(driver.driver_id);
  if (!partners || partners.size === 0) return null;
  for (const partnerId of partners) {
    if (shift.original_assigned_driver_id === partnerId) {
      return {
        rule: "R021",
        message: `Ad-hoc: forbidden to share a shift with ${partnerId}`
      };
    }
  }
  return null;
}

// src/eligibility.ts
var PASS = Object.freeze({
  eligible: true,
  block_reasons: []
});
function evaluateEligibility(shift, driver, state, ctx) {
  const s = ctx.settings;
  const block = checkBlackout(shift, ctx.blackout) ?? checkStatus(driver, s) ?? checkPreferredRequired(shift, driver, s) ?? checkLicense(shift, driver, s) ?? checkCertification(shift, driver, s) ?? checkPto(shift, driver, s) ?? checkAvailability(shift, driver, s) ?? checkAdHocExcludeFromDay(shift, driver, ctx) ?? checkAdHocBlackout(shift, driver, ctx) ?? checkAdHocPairForbidden(shift, driver, ctx) ?? checkSameDay(shift, state, s) ?? checkMaxDays(shift, state, ctx) ?? checkWeeklyCap(shift, driver, state, ctx) ?? checkWoc(shift, state, s) ?? checkMinRest(shift, state, s);
  if (block) return { eligible: false, block_reasons: [block] };
  return PASS;
}
function collectBlocks(shift, driver, state, ctx) {
  const s = ctx.settings;
  const reasons = [];
  const push = (r) => {
    if (r) reasons.push(r);
  };
  push(checkBlackout(shift, ctx.blackout));
  push(checkStatus(driver, s));
  push(checkPreferredRequired(shift, driver, s));
  push(checkLicense(shift, driver, s));
  push(checkCertification(shift, driver, s));
  push(checkPto(shift, driver, s));
  push(checkAvailability(shift, driver, s));
  push(checkAdHocExcludeFromDay(shift, driver, ctx));
  push(checkAdHocBlackout(shift, driver, ctx));
  push(checkAdHocPairForbidden(shift, driver, ctx));
  push(checkSameDay(shift, state, s));
  push(checkMaxDays(shift, state, ctx));
  push(checkWeeklyCap(shift, driver, state, ctx));
  push(checkWoc(shift, state, s));
  push(checkMinRest(shift, state, s));
  return reasons;
}

// src/plan.ts
function assignedRefOf(shift, source) {
  return {
    shift_id: shift.shift_id,
    date: shift.date,
    dow: shift.dow,
    start_ms: shift.start_ms,
    end_ms: shift.end_ms,
    duration_hours: shift.duration_hours,
    source
  };
}
function applyAssignment(ws, plan, driverId, source, score, scoreComponents) {
  plan.assignedDriverId = driverId;
  plan.source = source;
  plan.open = false;
  if (score !== void 0) plan.score = score;
  if (scoreComponents !== void 0) plan.scoreComponents = scoreComponents;
  const state = ws.states.get(driverId);
  if (state) state.assigned.push(assignedRefOf(plan.shift, source));
}

// src/steps/step1_5_locks.ts
function parseLockRule(raw, ctx) {
  if (raw.kind !== "driver_lock_to_day") return null;
  if (raw.hardness !== "hard") return null;
  const did = raw.payload?.driver_id;
  const dow = raw.payload?.dow;
  if (typeof did !== "string" || typeof dow !== "number") return null;
  if (!Number.isInteger(dow) || dow < 0 || dow > 6) return null;
  const driver = ctx.driverById.get(did);
  if (!driver) return null;
  return { driver, dow };
}
function applyDriverDayLocks(ctx, ws, constraints) {
  const warnings = [];
  const rules = [];
  for (const c of constraints) {
    const r = parseLockRule(c, ctx);
    if (r) rules.push(r);
  }
  if (rules.length === 0) return warnings;
  const relaxedSettings = {
    ...ctx.settings,
    availability_enforcement: false,
    availability_required: false,
    preferred_availability_required: false
  };
  const relaxedCtx = { ...ctx, settings: relaxedSettings };
  rules.sort((a, b) => {
    if (a.driver.driver_id !== b.driver.driver_id) {
      return a.driver.driver_id < b.driver.driver_id ? -1 : 1;
    }
    return a.dow - b.dow;
  });
  for (const rule of rules) {
    const candidates = ws.plans.filter((p) => p.open && dayOfWeek(p.shift.date) === rule.dow).sort((a, b) => {
      if (a.shift.date !== b.shift.date) {
        return a.shift.date < b.shift.date ? -1 : 1;
      }
      if (a.shift.start_ms !== b.shift.start_ms) {
        return a.shift.start_ms - b.shift.start_ms;
      }
      return a.shift.shift_id < b.shift.shift_id ? -1 : 1;
    });
    let placed = false;
    const blockTally = /* @__PURE__ */ new Map();
    const dowName = DOW_NAMES[rule.dow] || "day";
    for (const plan of candidates) {
      const state = ws.states.get(rule.driver.driver_id);
      if (!state) break;
      const cell = evaluateEligibility(plan.shift, rule.driver, state, relaxedCtx);
      if (cell.eligible) {
        applyAssignment(ws, plan, rule.driver.driver_id, "pin_lock");
        placed = true;
        break;
      }
      const reason = cell.block_reasons[0];
      if (reason && !blockTally.has(reason.rule)) {
        blockTally.set(reason.rule, reason);
      }
    }
    if (!placed) {
      const driverName = `${rule.driver.first_name} ${rule.driver.last_name}`.trim() || rule.driver.driver_id;
      let reasonText;
      if (candidates.length === 0) {
        reasonText = `no ${dowName} shift exists in this schedule week`;
      } else {
        const reasons = [...blockTally.values()];
        reasonText = reasons.length > 0 ? `${reasons.length === 1 ? "" : "primary reason: "}${reasons[0].message}` : "no eligible shift this week";
      }
      warnings.push({
        type: "pin_not_applied",
        driver_id: rule.driver.driver_id,
        message: `Pin \xB7 ${driverName} on ${dowName}s couldn't place this week \u2014 ${reasonText}.`
      });
    }
  }
  return warnings;
}

// src/steps/step2_driver_state.ts
function initDriverState(ctx, plans) {
  const states = /* @__PURE__ */ new Map();
  for (const d of ctx.drivers) {
    states.set(d.driver_id, { driver_id: d.driver_id, assigned: [] });
  }
  for (const plan of plans) {
    if (plan.assignedDriverId === null || plan.source === null) continue;
    const state = states.get(plan.assignedDriverId);
    if (state) state.assigned.push(assignedRefOf(plan.shift, plan.source));
  }
  for (const state of states.values()) {
    state.assigned.sort(
      (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
    );
  }
  return states;
}

// src/steps/step3_eligibility.ts
function buildEligibilityMatrix(ctx, ws) {
  const matrix = /* @__PURE__ */ new Map();
  for (const plan of ws.plans) {
    if (!plan.open) continue;
    const row = /* @__PURE__ */ new Map();
    for (const driver of ctx.drivers) {
      const state = ws.states.get(driver.driver_id);
      if (!state) continue;
      row.set(
        driver.driver_id,
        evaluateEligibility(plan.shift, driver, state, ctx)
      );
    }
    matrix.set(plan.shift.shift_id, row);
  }
  return matrix;
}
function recomputeDriverColumn(ctx, ws, matrix, driverId) {
  const driver = ctx.driverById.get(driverId);
  const state = ws.states.get(driverId);
  if (!driver || !state) return;
  for (const [shiftId, row] of matrix) {
    const plan = ws.planByShiftId.get(shiftId);
    if (!plan) continue;
    row.set(driverId, evaluateEligibility(plan.shift, driver, state, ctx));
  }
}

// src/steps/step4_patterns.ts
function computePatterns(ctx) {
  const windowWeeks = ctx.settings.history_window_weeks;
  const coldStartCutoff = Math.ceil(windowWeeks / 2);
  const weekStartEpoch = epochDay(ctx.scheduleWeek[0]);
  const byDriver = /* @__PURE__ */ new Map();
  for (const h of ctx.history) {
    const offset = weekStartEpoch - epochDay(h.date);
    if (offset < 1) continue;
    const weekIndex = Math.floor((offset - 1) / 7);
    if (weekIndex >= windowWeeks) continue;
    let weeks = byDriver.get(h.driver_id);
    if (!weeks) {
      weeks = /* @__PURE__ */ new Map();
      byDriver.set(h.driver_id, weeks);
    }
    let bucket = weeks.get(weekIndex);
    if (!bucket) {
      bucket = { dates: /* @__PURE__ */ new Set(), dows: /* @__PURE__ */ new Set(), hours: 0 };
      weeks.set(weekIndex, bucket);
    }
    bucket.dates.add(h.date);
    bucket.dows.add(dayOfWeek(h.date));
    bucket.hours += h.duration_hours ?? 10;
  }
  const patterns = /* @__PURE__ */ new Map();
  for (const driver of ctx.drivers) {
    const weeks = byDriver.get(driver.driver_id) ?? /* @__PURE__ */ new Map();
    const weeksWithData = weeks.size;
    const coldStart = weeksWithData < coldStartCutoff;
    const affinity = new Array(7).fill(0);
    if (coldStart) {
      affinity.fill(0.5);
    } else {
      for (let dow = 0; dow < 7; dow++) {
        let count = 0;
        for (const bucket of weeks.values()) {
          if (bucket.dows.has(dow)) count += 1;
        }
        affinity[dow] = count / windowWeeks;
      }
    }
    let totalDates = 0;
    let totalHours = 0;
    for (const bucket of weeks.values()) {
      totalDates += bucket.dates.size;
      totalHours += bucket.hours;
    }
    const denom = weeksWithData > 0 ? weeksWithData : 1;
    patterns.set(driver.driver_id, {
      driver_id: driver.driver_id,
      day_of_week_affinity: affinity,
      avg_weekly_days: weeksWithData > 0 ? totalDates / denom : 0,
      avg_weekly_hours: weeksWithData > 0 ? totalHours / denom : 0,
      weeks_with_data: weeksWithData,
      cold_start: coldStart
    });
  }
  return patterns;
}

// src/rules/r015_method.ts
function availabilityBreadth(driver) {
  if (driver.saved_availability === null) return 7;
  let count = 0;
  for (const key of Object.keys(driver.saved_availability)) {
    const windows = driver.saved_availability[key];
    if (windows && windows.length > 0) count += 1;
  }
  return count;
}
function strHash(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function orderDrivers(ctx, states) {
  const method = ctx.settings.scheduling_method;
  const drivers = [...ctx.drivers];
  const randomKeys = /* @__PURE__ */ new Map();
  if (method === "random") {
    for (const d of drivers) {
      randomKeys.set(d.driver_id, strHash(d.driver_id + ":" + ctx.scheduleWeek[0]));
    }
  }
  const fairKeys = /* @__PURE__ */ new Map();
  if (method === "fair_rotation") {
    const weekStartDay = epochDay(ctx.scheduleWeek[0]);
    const lastByDriver = /* @__PURE__ */ new Map();
    for (const h of ctx.history) {
      const cur = lastByDriver.get(h.driver_id);
      if (cur === void 0 || h.date > cur) {
        lastByDriver.set(h.driver_id, h.date);
      }
    }
    for (const d of drivers) {
      const st = states.get(d.driver_id);
      const assigned = st ? st.assigned : [];
      let last = lastByDriver.get(d.driver_id);
      for (const a of assigned) {
        if (last === void 0 || a.date > last) last = a.date;
      }
      fairKeys.set(d.driver_id, {
        hours: st ? workHoursInWindow(st, ctx.scheduleWeek) : 0,
        days: st ? uniqueDatesInWindow(st, ctx.scheduleWeek).size : 0,
        sinceLast: last === void 0 ? Number.MAX_SAFE_INTEGER : weekStartDay - epochDay(last)
      });
    }
  }
  drivers.sort((a, b) => {
    switch (method) {
      case "fair_rotation": {
        const ka = fairKeys.get(a.driver_id);
        const kb = fairKeys.get(b.driver_id);
        if (ka.hours !== kb.hours) return ka.hours - kb.hours;
        if (ka.days !== kb.days) return ka.days - kb.days;
        if (ka.sinceLast !== kb.sinceLast) return ka.sinceLast - kb.sinceLast;
        return compareSeniority(a, b);
      }
      case "seniority":
        return compareSeniority(a, b);
      case "full_time_priority": {
        if (a.employment_type !== b.employment_type) {
          return a.employment_type === "full_time" ? -1 : 1;
        }
        return compareSeniority(a, b);
      }
      case "alphabetical": {
        if (a.sort_key !== b.sort_key) return a.sort_key < b.sort_key ? -1 : 1;
        return a.driver_id < b.driver_id ? -1 : 1;
      }
      case "attendance_priority": {
        const sa = a.attendance_score ?? 50;
        const sb = b.attendance_score ?? 50;
        if (sa !== sb) return sb - sa;
        return compareSeniority(a, b);
      }
      case "availability_first": {
        const ba = availabilityBreadth(a);
        const bb = availabilityBreadth(b);
        if (ba !== bb) return bb - ba;
        return compareSeniority(a, b);
      }
      case "random": {
        const ka = randomKeys.get(a.driver_id) ?? 0;
        const kb = randomKeys.get(b.driver_id) ?? 0;
        if (ka !== kb) return ka - kb;
        return a.driver_id < b.driver_id ? -1 : 1;
      }
    }
  });
  if (ctx.settings.attendance_penalty) {
    const normal = [];
    const penalized = [];
    for (const d of drivers) {
      (d.attendance_final ? penalized : normal).push(d);
    }
    return [...normal, ...penalized];
  }
  return drivers;
}
function methodPoints(rank, driverCount) {
  if (driverCount <= 1) return 20;
  return 20 * (driverCount - rank) / (driverCount - 1);
}

// src/rules/r012_patterns.ts
var HIGH_AFFINITY_THRESHOLD = 0.75;
function patternMaxBonus(strength) {
  switch (strength) {
    case "off":
      return 0;
    case "low":
      return 10;
    case "medium":
      return 25;
    case "high":
      return 50;
  }
}
function historicalPoints(pattern, dow, strength) {
  if (strength === "off") return 0;
  return pattern.day_of_week_affinity[dow] * patternMaxBonus(strength);
}

// src/steps/step5_pattern_pass.ts
function runPatternPass(ctx, ws, matrix) {
  if (ctx.settings.historical_pattern_protection !== "high") return;
  for (const driver of orderDrivers(ctx, ws.states)) {
    const pattern = ctx.patterns.get(driver.driver_id);
    const state = ws.states.get(driver.driver_id);
    if (!pattern || !state) continue;
    const target = Math.floor(
      Math.min(pattern.avg_weekly_days, ctx.settings.max_days)
    );
    let budget = target - uniqueDatesInWindow(state, ctx.scheduleWeek).size;
    if (budget <= 0) continue;
    const candidates = [];
    for (const plan of ws.plans) {
      if (!plan.open) continue;
      if (pattern.day_of_week_affinity[plan.shift.dow] < HIGH_AFFINITY_THRESHOLD) {
        continue;
      }
      candidates.push(plan);
    }
    candidates.sort((a, b) => {
      const fa = pattern.day_of_week_affinity[a.shift.dow];
      const fb = pattern.day_of_week_affinity[b.shift.dow];
      if (fa !== fb) return fb - fa;
      if (a.shift.date !== b.shift.date) {
        return a.shift.date < b.shift.date ? -1 : 1;
      }
      if (a.shift.start_ms !== b.shift.start_ms) {
        return a.shift.start_ms - b.shift.start_ms;
      }
      return a.shift.shift_id < b.shift.shift_id ? -1 : 1;
    });
    for (const plan of candidates) {
      if (budget <= 0) break;
      if (!plan.open) continue;
      const cell = matrix.get(plan.shift.shift_id)?.get(driver.driver_id);
      if (!cell || !cell.eligible) continue;
      applyAssignment(ws, plan, driver.driver_id, "pattern_pass");
      matrix.delete(plan.shift.shift_id);
      recomputeDriverColumn(ctx, ws, matrix, driver.driver_id);
      budget -= 1;
    }
  }
}

// src/rules/r013_attendance.ts
var ATTENDANCE_WEIGHT = {
  low: 0.4,
  medium: 1,
  high: 1.6
};
function attendanceScore(driver) {
  return driver.attendance_score ?? 50;
}
function attendancePoints(driver, settings) {
  if (!settings.attendance_scheduling) return 0;
  const mult = ATTENDANCE_WEIGHT[settings.attendance_weight];
  return (attendanceScore(driver) - 50) / 50 * 25 * mult;
}

// src/rules/r018_consecutive.ts
function consecutivePoints(shift, state, settings) {
  if (!settings.consecutive_working_days) return 0;
  const dates = assignedDates(state);
  dates.delete(shift.date);
  const hasPrev = dates.has(addDays(shift.date, -1));
  const hasNext = dates.has(addDays(shift.date, 1));
  if (hasPrev && hasNext) return 15;
  if (hasPrev || hasNext) return 10;
  return 0;
}

// src/rules/r022_target_days.ts
function targetCapPoints(shift, state, ctx, settings) {
  const target = settings.target_days_per_week;
  if (target <= 0) return 0;
  const dates = uniqueDatesInWindow(state, ctx.scheduleWeek);
  const isSameDate = dates.has(shift.date);
  const projected = isSameDate ? dates.size : dates.size + 1;
  if (projected <= target) return 0;
  return -(projected - target) * 100;
}

// src/steps/step7_scoring.ts
function computeScore(ctx, shift, driver, state, methodRank) {
  const pattern = ctx.patterns.get(driver.driver_id);
  const historical = pattern === void 0 ? 0 : Math.round(
    historicalPoints(
      pattern,
      shift.dow,
      ctx.settings.historical_pattern_protection
    )
  );
  const attendance = Math.round(attendancePoints(driver, ctx.settings));
  const preferred = Math.round(preferredPoints(shift, driver, ctx.settings));
  const consecutive = Math.round(
    consecutivePoints(shift, state, ctx.settings)
  );
  const method = Math.round(methodPoints(methodRank, ctx.drivers.length));
  const performance = 0;
  const target_days = Math.round(
    targetCapPoints(shift, state, ctx, ctx.settings)
  );
  const components = {
    historical,
    attendance,
    preferred,
    consecutive,
    method,
    performance,
    target_days
  };
  return {
    components,
    total: historical + attendance + preferred + consecutive + method + performance + target_days
  };
}

// src/steps/step6_assign.ts
function planInPhase(plan, phase) {
  const dot = isDotRoute(plan.shift);
  if (phase === "dot") return dot;
  if (dot) return false;
  const xl = plan.shift.route_type === "xl";
  return phase === "xl" ? xl : !xl;
}
function bestShiftForDriver(ctx, ws, matrix, driver, methodRank, phase) {
  const state = ws.states.get(driver.driver_id);
  if (!state) return null;
  let best = null;
  for (const [shiftId, row] of matrix) {
    const cell = row.get(driver.driver_id);
    if (!cell || !cell.eligible) continue;
    const plan = ws.planByShiftId.get(shiftId);
    if (!plan || !plan.open || !planInPhase(plan, phase)) continue;
    const { total, components } = computeScore(ctx, plan.shift, driver, state, methodRank);
    if (best === null || isBetter(plan, total, best, ctx.settings.rotation_start_day)) {
      best = { plan, score: total, components };
    }
  }
  return best;
}
function rotationRank(dow, startDow) {
  return (dow - startDow + 7) % 7;
}
function isBetter(plan, score, best, startDow) {
  if (score !== best.score) return score > best.score;
  const a = plan.shift;
  const b = best.plan.shift;
  const ra = rotationRank(a.dow, startDow);
  const rb = rotationRank(b.dow, startDow);
  if (ra !== rb) return ra < rb;
  if (a.date !== b.date) return a.date < b.date;
  if (a.start_ms !== b.start_ms) return a.start_ms < b.start_ms;
  return a.shift_id < b.shift_id;
}
function isAtOrOverTarget(ctx, ws, driver) {
  const target = ctx.settings.target_days_per_week;
  if (target <= 0) return false;
  const state = ws.states.get(driver.driver_id);
  if (!state) return false;
  return uniqueDatesInWindow(state, ctx.scheduleWeek).size >= target;
}
function runFillCycle(ctx, ws, matrix, phase, order, rankMap, driverSkip) {
  const assignOne = (driver) => {
    if (driverSkip(driver)) return false;
    const rank = rankMap.get(driver.driver_id) ?? order.length;
    const best = bestShiftForDriver(ctx, ws, matrix, driver, rank, phase);
    if (!best) return false;
    applyAssignment(ws, best.plan, driver.driver_id, "auto_fill", best.score, best.components);
    matrix.delete(best.plan.shift.shift_id);
    recomputeDriverColumn(ctx, ws, matrix, driver.driver_id);
    return true;
  };
  if (ctx.settings.assignment_mode === "sequential_fill") {
    for (const driver of order) {
      while (assignOne(driver)) {
      }
    }
    return;
  }
  const batch = Math.max(1, ctx.settings.rotation_batch_size);
  let progress = true;
  while (progress) {
    progress = false;
    for (const driver of order) {
      for (let i = 0; i < batch; i++) {
        if (assignOne(driver)) progress = true;
        else break;
      }
    }
  }
}
function runPhase(ctx, ws, matrix, phase) {
  const order = orderDrivers(ctx, ws.states);
  const rankMap = /* @__PURE__ */ new Map();
  order.forEach((d, i) => rankMap.set(d.driver_id, i + 1));
  const fcaLast = ctx.settings.attendance_penalty;
  const skips = fcaLast ? [
    // A — clean drivers under target.
    (d) => d.attendance_final || isAtOrOverTarget(ctx, ws, d),
    // B — clean drivers past target (soft-cap escape).
    (d) => d.attendance_final,
    // C — Final-corrective drivers under target.
    (d) => !d.attendance_final || isAtOrOverTarget(ctx, ws, d),
    // D — Final-corrective drivers past target (last resort).
    (d) => !d.attendance_final
  ] : [
    // Pass A — only drivers UNDER their target_days_per_week can
    // claim. Re-evaluated per call (day-count grows as they're
    // assigned), so a driver naturally drops out of Pass A once they
    // hit target. Target 0 collapses to "always true" — no soft cap.
    (d) => isAtOrOverTarget(ctx, ws, d),
    // Pass B — coverage escape hatch. Any still-eligible driver may
    // claim remaining open shifts, even past their target. This is
    // the OT mode — only kicks in when Pass A couldn't cover.
    () => false
  ];
  for (const skip of skips) {
    runFillCycle(ctx, ws, matrix, phase, order, rankMap, skip);
  }
}
function runMainPass(ctx, ws, matrix) {
  runPhase(ctx, ws, matrix, "dot");
  runPhase(ctx, ws, matrix, "xl");
  runPhase(ctx, ws, matrix, "standard");
}

// src/steps/step8_optimize.ts
var MIN_IMPROVEMENT = 5;
var MAX_ITERATIONS = 3;
function stateWithout(state, shiftId) {
  return {
    driver_id: state.driver_id,
    assigned: state.assigned.filter((a) => a.shift_id !== shiftId)
  };
}
function isSwappable(plan) {
  return plan.assignedDriverId !== null && (plan.source === "auto_fill" || plan.source === "pattern_pass" || plan.source === "swap");
}
function runOptimization(ctx, ws) {
  let iterations = 0;
  for (let i = 0; i < MAX_ITERATIONS; i++) {
    const swap = findBestSwap(ctx, ws);
    if (!swap) break;
    applySwap(ws, swap);
    iterations += 1;
  }
  return iterations;
}
function findBestSwap(ctx, ws) {
  const rank = /* @__PURE__ */ new Map();
  orderDrivers(ctx, ws.states).forEach((d, i) => rank.set(d.driver_id, i + 1));
  const swappable = ws.plans.filter(isSwappable);
  let best = null;
  for (let i = 0; i < swappable.length; i++) {
    for (let j = i + 1; j < swappable.length; j++) {
      const p1 = swappable[i];
      const p2 = swappable[j];
      const d1 = p1.assignedDriverId;
      const d2 = p2.assignedDriverId;
      if (d1 === d2) continue;
      const driver1 = ctx.driverById.get(d1);
      const driver2 = ctx.driverById.get(d2);
      const state1 = ws.states.get(d1);
      const state2 = ws.states.get(d2);
      if (!driver1 || !driver2 || !state1 || !state2) continue;
      const base1 = stateWithout(state1, p1.shift.shift_id);
      const base2 = stateWithout(state2, p2.shift.shift_id);
      const d2TakesP1 = evaluateEligibility(p1.shift, driver2, base2, ctx);
      const d1TakesP2 = evaluateEligibility(p2.shift, driver1, base1, ctx);
      if (!d2TakesP1.eligible || !d1TakesP2.eligible) continue;
      const current = computeScore(ctx, p1.shift, driver1, base1, rank.get(d1) ?? 0).total + computeScore(ctx, p2.shift, driver2, base2, rank.get(d2) ?? 0).total;
      const swapped = computeScore(ctx, p1.shift, driver2, base2, rank.get(d2) ?? 0).total + computeScore(ctx, p2.shift, driver1, base1, rank.get(d1) ?? 0).total;
      const delta = swapped - current;
      if (delta < MIN_IMPROVEMENT) continue;
      if (best === null || delta > best.delta) {
        best = { p1, p2, delta };
      }
    }
  }
  return best;
}
function applySwap(ws, swap) {
  const { p1, p2 } = swap;
  const d1 = p1.assignedDriverId;
  const d2 = p2.assignedDriverId;
  const state1 = ws.states.get(d1);
  const state2 = ws.states.get(d2);
  if (!state1 || !state2) return;
  state1.assigned = state1.assigned.filter(
    (a) => a.shift_id !== p1.shift.shift_id
  );
  state2.assigned = state2.assigned.filter(
    (a) => a.shift_id !== p2.shift.shift_id
  );
  p1.assignedDriverId = d2;
  p1.source = "swap";
  p2.assignedDriverId = d1;
  p2.source = "swap";
  state2.assigned.push(assignedRefOf(p1.shift, "swap"));
  state1.assigned.push(assignedRefOf(p2.shift, "swap"));
  state1.assigned.sort(
    (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
  );
  state2.assigned.sort(
    (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
  );
}

// src/steps/step8b_preferred_enhancement.ts
function runCount(dates) {
  const sorted = [...new Set(dates)].sort();
  if (sorted.length === 0) return 0;
  let runs = 1;
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] !== addDays(sorted[i - 1], 1)) runs += 1;
  }
  return runs;
}
function stateWithout2(state, shiftId) {
  return {
    driver_id: state.driver_id,
    assigned: state.assigned.filter((a) => a.shift_id !== shiftId)
  };
}
function sortBySid(state) {
  state.assigned.sort(
    (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
  );
}
function applySwap2(ws, planA, planB) {
  const a = planA.assignedDriverId;
  const b = planB.assignedDriverId;
  const stateA = ws.states.get(a);
  const stateB = ws.states.get(b);
  if (!stateA || !stateB) return;
  stateA.assigned = stateA.assigned.filter(
    (x) => x.shift_id !== planA.shift.shift_id
  );
  stateB.assigned = stateB.assigned.filter(
    (x) => x.shift_id !== planB.shift.shift_id
  );
  planA.assignedDriverId = b;
  planA.source = "swap";
  planB.assignedDriverId = a;
  planB.source = "swap";
  stateB.assigned.push(assignedRefOf(planA.shift, "swap"));
  stateA.assigned.push(assignedRefOf(planB.shift, "swap"));
  sortBySid(stateA);
  sortBySid(stateB);
}
function onePass(ctx, ws, allowScatter) {
  const order = orderDrivers(ctx, ws.states);
  for (const a of order) {
    const stateA = ws.states.get(a.driver_id);
    if (!stateA) continue;
    const aRefs = [...stateA.assigned].sort(
      (x, y) => x.date < y.date ? -1 : x.date > y.date ? 1 : 0
    );
    for (const refA of aRefs) {
      const planA = ws.planByShiftId.get(refA.shift_id);
      if (!planA || planA.assignedDriverId !== a.driver_id) continue;
      if (planA.source === "locked" || planA.source === "preserved" || planA.source === "pin_lock") continue;
      if (inPreferredWindow(planA.shift, a)) continue;
      for (const b of order) {
        if (b.driver_id === a.driver_id) continue;
        const stateB = ws.states.get(b.driver_id);
        if (!stateB) continue;
        if (!inPreferredWindow(planA.shift, b)) continue;
        const bRefs = [...stateB.assigned].sort(
          (x, y) => x.date < y.date ? -1 : x.date > y.date ? 1 : 0
        );
        for (const refB of bRefs) {
          if (refB.date === refA.date) continue;
          const planB = ws.planByShiftId.get(refB.shift_id);
          if (!planB || planB.assignedDriverId !== b.driver_id) continue;
          if (planB.source === "locked" || planB.source === "preserved" || planB.source === "pin_lock") continue;
          if (inPreferredWindow(planB.shift, b)) continue;
          if (!inPreferredWindow(planB.shift, a)) continue;
          const baseA = stateWithout2(stateA, refA.shift_id);
          const baseB = stateWithout2(stateB, refB.shift_id);
          if (!evaluateEligibility(planB.shift, a, baseA, ctx).eligible) {
            continue;
          }
          if (!evaluateEligibility(planA.shift, b, baseB, ctx).eligible) {
            continue;
          }
          if (!allowScatter) {
            const aBefore = stateA.assigned.map((x) => x.date);
            const bBefore = stateB.assigned.map((x) => x.date);
            const aAfter = aBefore.filter((d) => d !== refA.date).concat(refB.date);
            const bAfter = bBefore.filter((d) => d !== refB.date).concat(refA.date);
            if (runCount(aAfter) > runCount(aBefore)) continue;
            if (runCount(bAfter) > runCount(bBefore)) continue;
          }
          applySwap2(ws, planA, planB);
          return true;
        }
      }
    }
  }
  return false;
}
function runPreferredEnhancement(ctx, ws) {
  if (!ctx.settings.preferred_enhancement) return 0;
  let swaps = 0;
  if (ctx.settings.preferred_enhancement_contiguous) {
    while (onePass(ctx, ws, false)) swaps += 1;
  }
  if (ctx.settings.preferred_enhancement_extra) {
    while (onePass(ctx, ws, true)) swaps += 1;
  }
  return swaps;
}

// src/steps/step8c_affinity_enhancement.ts
function affinityOf(driver, dow) {
  const a = driver.weekday_affinity;
  return a && a.length === 7 ? a[dow] : 0;
}
function stateWithout3(state, shiftId) {
  return {
    driver_id: state.driver_id,
    assigned: state.assigned.filter((a) => a.shift_id !== shiftId)
  };
}
function sortBySid2(state) {
  state.assigned.sort(
    (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
  );
}
function applySwap3(ws, planA, planB) {
  const a = planA.assignedDriverId;
  const b = planB.assignedDriverId;
  const stateA = ws.states.get(a);
  const stateB = ws.states.get(b);
  if (!stateA || !stateB) return;
  stateA.assigned = stateA.assigned.filter(
    (x) => x.shift_id !== planA.shift.shift_id
  );
  stateB.assigned = stateB.assigned.filter(
    (x) => x.shift_id !== planB.shift.shift_id
  );
  planA.assignedDriverId = b;
  planA.source = "swap";
  planB.assignedDriverId = a;
  planB.source = "swap";
  stateB.assigned.push(assignedRefOf(planA.shift, "swap"));
  stateA.assigned.push(assignedRefOf(planB.shift, "swap"));
  sortBySid2(stateA);
  sortBySid2(stateB);
}
function onePassForDay(ctx, ws, day, locked) {
  const order = orderDrivers(ctx, ws.states);
  const driverById = new Map(order.map((d) => [d.driver_id, d]));
  for (const planA of ws.plans) {
    if (planA.shift.dow !== day) continue;
    if (!planA.assignedDriverId || locked.has(planA.shift.shift_id)) continue;
    if (planA.source === "locked" || planA.source === "preserved" || planA.source === "pin_lock") continue;
    const a = driverById.get(planA.assignedDriverId);
    const stateA = ws.states.get(planA.assignedDriverId);
    if (!a || !stateA) continue;
    let best = null;
    for (const planB of ws.plans) {
      if (planB.shift.dow === day) continue;
      if (!planB.assignedDriverId || locked.has(planB.shift.shift_id)) continue;
      if (planB.source === "locked" || planB.source === "preserved" || planB.source === "pin_lock") continue;
      if (planB.assignedDriverId === a.driver_id) continue;
      const b = driverById.get(planB.assignedDriverId);
      const stateB = ws.states.get(planB.assignedDriverId);
      if (!b || !stateB) continue;
      const dA = planA.shift.dow;
      const dB = planB.shift.dow;
      const before = affinityOf(a, dA) + affinityOf(b, dB);
      const after = affinityOf(a, dB) + affinityOf(b, dA);
      if (after <= before) continue;
      if (affinityOf(b, dA) <= affinityOf(a, dA)) continue;
      const baseA = stateWithout3(stateA, planA.shift.shift_id);
      const baseB = stateWithout3(stateB, planB.shift.shift_id);
      if (!evaluateEligibility(planB.shift, a, baseA, ctx).eligible) continue;
      if (!evaluateEligibility(planA.shift, b, baseB, ctx).eligible) continue;
      const gain = after - before;
      if (best === null || gain > best.gain || gain === best.gain && planB.shift.shift_id < best.planB.shift.shift_id) {
        best = { planB, gain };
      }
    }
    if (best) {
      applySwap3(ws, planA, best.planB);
      return true;
    }
  }
  return false;
}
function runAffinityEnhancement(ctx, ws) {
  if (!ctx.settings.affinity_enhancement) return 0;
  const locked = /* @__PURE__ */ new Set();
  let swaps = 0;
  for (const day of ctx.settings.affinity_day_order) {
    while (onePassForDay(ctx, ws, day, locked)) swaps += 1;
    for (const plan of ws.plans) {
      if (plan.shift.dow === day && plan.assignedDriverId) {
        locked.add(plan.shift.shift_id);
      }
    }
  }
  return swaps;
}

// src/steps/step8d_fifth_day_fill.ts
function runFifthDayFill(ctx, ws) {
  if (!ctx.settings.fifth_day_fill) return 0;
  const relaxedCtx = {
    ...ctx,
    settings: {
      ...ctx.settings,
      max_days_enforcement: false,
      ...ctx.settings.fifth_day_override_availability ? { availability_enforcement: false, availability_required: false } : {}
    }
  };
  const order = orderDrivers(ctx, ws.states);
  const extraGiven = /* @__PURE__ */ new Set();
  const openPlans = ws.plans.filter((p) => p.open).sort(
    (a, b) => a.shift.date !== b.shift.date ? a.shift.date < b.shift.date ? -1 : 1 : a.shift.start_ms !== b.shift.start_ms ? a.shift.start_ms - b.shift.start_ms : a.shift.shift_id < b.shift.shift_id ? -1 : 1
  );
  let filled = 0;
  for (const plan of openPlans) {
    for (const driver of order) {
      if (!driver.fifth_day_ok) continue;
      if (extraGiven.has(driver.driver_id)) continue;
      const state = ws.states.get(driver.driver_id);
      if (!state) continue;
      if (!evaluateEligibility(plan.shift, driver, state, relaxedCtx).eligible) {
        continue;
      }
      applyAssignment(ws, plan, driver.driver_id, "fifth_day");
      extraGiven.add(driver.driver_id);
      filled += 1;
      break;
    }
  }
  return filled;
}

// src/steps/step9_validate.ts
function without(state, shiftId) {
  return {
    driver_id: state.driver_id,
    assigned: state.assigned.filter((a) => a.shift_id !== shiftId)
  };
}
function validate(ctx, ws) {
  const violations = [];
  const warnings = [];
  const s = ctx.settings;
  const week = ctx.scheduleWeek;
  for (const plan of ws.plans) {
    const driverId = plan.assignedDriverId;
    if (driverId === null) continue;
    const driver = ctx.driverById.get(driverId);
    if (!driver) {
      violations.push({
        severity: "critical",
        rule: "R002",
        shift_id: plan.shift.shift_id,
        driver_id: driverId,
        message: `Assigned driver "${driverId}" not found in driver list`
      });
      continue;
    }
    const state = ws.states.get(driverId);
    const blocks = collectBlocks(
      plan.shift,
      driver,
      without(state, plan.shift.shift_id),
      ctx
    );
    if (blocks.length === 0) continue;
    const acknowledged = plan.source === "locked" && plan.shift.override_ack_by !== null && plan.shift.override_ack_by !== "";
    const tag = plan.source === "locked" ? " (locked manual override)" : plan.source === "preserved" ? " (preserved assignment)" : "";
    for (const b of blocks) {
      violations.push({
        severity: acknowledged ? "acknowledged" : "critical",
        rule: b.rule,
        shift_id: plan.shift.shift_id,
        driver_id: driverId,
        message: b.message + tag
      });
    }
  }
  for (const driver of ctx.drivers) {
    if (s.license_enforcement && driver.license_expiration_date === null) {
      warnings.push({
        type: "license_expiration_missing",
        driver_id: driver.driver_id,
        message: `Driver ${driver.driver_id} has no license expiration date on file`
      });
    }
    const state = ws.states.get(driver.driver_id);
    if (!state) continue;
    const weekDates = uniqueDatesInWindow(state, week);
    if (weekDates.size === 0) continue;
    if (s.max_days_enforcement && weekDates.size >= s.max_days - 1) {
      warnings.push({
        type: "near_max_days",
        driver_id: driver.driver_id,
        message: `Driver ${driver.driver_id} is at ${weekDates.size}/${s.max_days} days`
      });
    }
    if (s.weekly_hour_cap_enforcement) {
      const work = workHoursInWindow(state, week);
      const pto = s.pto_counts_toward_cap ? ptoHoursInWindow(driver, week, s) : 0;
      const counted = work + pto;
      if (counted <= s.weekly_hour_cap && s.weekly_hour_cap - counted <= 10) {
        warnings.push({
          type: "near_weekly_cap",
          driver_id: driver.driver_id,
          message: `Driver ${driver.driver_id} is at ${counted}/${s.weekly_hour_cap} hours`
        });
      }
    }
    if (driver.attendance_score !== null && attendanceScore(driver) < 60) {
      warnings.push({
        type: "low_attendance_assigned",
        driver_id: driver.driver_id,
        message: `Driver ${driver.driver_id} assigned with low attendance score ${driver.attendance_score}`
      });
    }
  }
  for (const plan of ws.plans) {
    const driverId = plan.assignedDriverId;
    if (driverId === null) continue;
    const driver = ctx.driverById.get(driverId);
    if (!driver) continue;
    if (s.preferred_availability_priority && driver.preferred_availability !== null && !inPreferredWindow(plan.shift, driver)) {
      warnings.push({
        type: "assigned_outside_preferred",
        shift_id: plan.shift.shift_id,
        driver_id: driverId,
        message: `${plan.shift.shift_id} is outside ${driverId}'s preferred availability`
      });
    }
    if (s.historical_pattern_protection !== "off") {
      const pattern = ctx.patterns.get(driverId);
      if (pattern && pattern.day_of_week_affinity[plan.shift.dow] === 0) {
        warnings.push({
          type: "historical_pattern_disrupted",
          shift_id: plan.shift.shift_id,
          driver_id: driverId,
          message: `${driverId} assigned to a 0-affinity day on ${plan.shift.date}`
        });
      }
    }
  }
  return { violations, warnings };
}

// src/steps/step10_explain.ts
var HARD_CHECKS = [
  "R002",
  "R003",
  "R004",
  "R005",
  "R006",
  "R007",
  "R008",
  "R009",
  "R010",
  "R011",
  "R019",
  "R020",
  "R021"
];
function clock(min) {
  const m = (min % 1440 + 1440) % 1440;
  return `${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
}
function buildAssignmentExplanations(ctx, ws, warnings) {
  const rank = /* @__PURE__ */ new Map();
  orderDrivers(ctx, ws.states).forEach((d, i) => rank.set(d.driver_id, i + 1));
  const warningsByShift = /* @__PURE__ */ new Map();
  for (const w of warnings) {
    if (w.shift_id === void 0) continue;
    const list = warningsByShift.get(w.shift_id) ?? [];
    list.push(w.type);
    warningsByShift.set(w.shift_id, list);
  }
  const out = [];
  for (const plan of ws.plans) {
    const driverId = plan.assignedDriverId;
    if (driverId === null) continue;
    const driver = ctx.driverById.get(driverId);
    const state = ws.states.get(driverId);
    if (!driver || !state) continue;
    const base = {
      driver_id: driverId,
      assigned: state.assigned.filter(
        (a) => a.shift_id !== plan.shift.shift_id
      )
    };
    const { components, total } = computeScore(
      ctx,
      plan.shift,
      driver,
      base,
      rank.get(driverId) ?? ctx.drivers.length
    );
    const dow = DOW_NAMES[plan.shift.dow];
    out.push({
      shift_id: plan.shift.shift_id,
      driver_id: driverId,
      decision: "assigned",
      hard_checks_passed: [...HARD_CHECKS],
      score_components: components,
      total_score: total,
      warnings: warningsByShift.get(plan.shift.shift_id) ?? [],
      summary: `Assigned ${driver.first_name} ${driver.last_name} to ${dow} ${plan.shift.date} (${plan.shift.route_type}) via ${plan.source}; score ${total} [historical ${components.historical}, attendance ${components.attendance}, preferred ${components.preferred}, consecutive ${components.consecutive}, method ${components.method}, target_days ${components.target_days}].`
    });
  }
  return out;
}
function buildUncovered(ctx, ws) {
  const out = [];
  for (const plan of ws.plans) {
    if (plan.assignedDriverId !== null || plan.closed) continue;
    const byRule = /* @__PURE__ */ new Map();
    for (const driver of ctx.drivers) {
      const state = ws.states.get(driver.driver_id);
      if (!state) continue;
      const cell = evaluateEligibility(plan.shift, driver, state, ctx);
      if (cell.eligible) continue;
      const reason = cell.block_reasons[0];
      const entry = byRule.get(reason.rule);
      if (entry) entry.count += 1;
      else byRule.set(reason.rule, { count: 1, message: reason.message });
    }
    const top = [...byRule.entries()].map(([rule, v]) => ({ rule, count: v.count, message: v.message })).sort(
      (a, b) => a.count !== b.count ? b.count - a.count : a.rule < b.rule ? -1 : 1
    );
    const dow = DOW_NAMES[plan.shift.dow];
    const detail = top.length > 0 ? top.map((r) => `${r.count} ${r.message}`).join("; ") : "no eligible drivers available";
    out.push({
      shift_id: plan.shift.shift_id,
      top_block_reasons: top,
      summary: `${dow} ${plan.shift.date} ${clock(plan.shift.start_min)} ${plan.shift.route_type} route uncovered: ${detail}.`
    });
  }
  return out;
}
function buildUnscheduledDrivers(ctx, ws) {
  const out = [];
  for (const driver of ctx.drivers) {
    const state = ws.states.get(driver.driver_id);
    if (!state || state.assigned.length > 0) continue;
    let eligibleSomewhere = false;
    const byRule = /* @__PURE__ */ new Map();
    for (const plan of ws.plans) {
      if (plan.closed) continue;
      const cell = evaluateEligibility(plan.shift, driver, state, ctx);
      if (cell.eligible) {
        eligibleSomewhere = true;
        continue;
      }
      if (plan.assignedDriverId === null) {
        const reason = cell.block_reasons[0];
        const entry = byRule.get(reason.rule);
        if (entry) entry.count += 1;
        else byRule.set(reason.rule, { count: 1, message: reason.message });
      }
    }
    out.push({
      driver_id: driver.driver_id,
      eligible_somewhere: eligibleSomewhere,
      block_reasons: [...byRule.entries()].map(([rule, v]) => ({ rule, count: v.count, message: v.message })).sort(
        (a, b) => a.count !== b.count ? b.count - a.count : a.rule < b.rule ? -1 : 1
      )
    });
  }
  return out;
}

// src/orchestrator.ts
function buildContext(input) {
  if (!input || typeof input !== "object") {
    throw new EngineError("Engine input must be an object");
  }
  if (!input.schedule_week_start || !isValidDate(input.schedule_week_start)) {
    throw new EngineError("Invalid or missing schedule_week_start");
  }
  if (!Array.isArray(input.shifts) || !Array.isArray(input.drivers)) {
    throw new EngineError("Engine input requires shifts[] and drivers[]");
  }
  const settings = validateSettings(input.settings);
  const shifts = input.shifts.map(normalizeShift);
  shifts.sort(
    (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
  );
  const seenShift = /* @__PURE__ */ new Set();
  for (const s of shifts) {
    if (seenShift.has(s.shift_id)) {
      throw new EngineError(`Duplicate shift_id: ${s.shift_id}`);
    }
    seenShift.add(s.shift_id);
  }
  const droppedDrivers = [];
  const drivers = [];
  for (const raw of input.drivers) {
    try {
      drivers.push(normalizeDriver(raw));
    } catch (e) {
      droppedDrivers.push({
        driver_id: raw && raw.driver_id != null ? String(raw.driver_id) : "(no id)",
        error: e instanceof Error && e.message || String(e)
      });
    }
  }
  if (droppedDrivers.length && typeof console !== "undefined" && console.warn) {
    console.warn(
      `[scheduling-engine] dropped ${droppedDrivers.length} malformed driver record(s):`,
      droppedDrivers
    );
  }
  drivers.sort(
    (a, b) => a.driver_id < b.driver_id ? -1 : a.driver_id > b.driver_id ? 1 : 0
  );
  const driverById = /* @__PURE__ */ new Map();
  for (const d of drivers) {
    if (driverById.has(d.driver_id)) {
      throw new EngineError(`Duplicate driver_id: ${d.driver_id}`);
    }
    driverById.set(d.driver_id, d);
  }
  const dsp = input.dsp ?? {};
  const weekStartDay = dsp.dsp_week_start_day ?? 0;
  if (!Number.isInteger(weekStartDay) || weekStartDay < 0 || weekStartDay > 6) {
    throw new EngineError("dsp_week_start_day must be an integer 0-6");
  }
  const blackout = /* @__PURE__ */ new Set();
  for (const d of dsp.dsp_blackout_dates ?? []) {
    if (!isValidDate(d)) throw new EngineError(`Invalid blackout date: ${d}`);
    blackout.add(d);
  }
  let payPeriod = null;
  if (input.pay_period) {
    if (!isValidDate(input.pay_period.start) || !isValidDate(input.pay_period.end) || input.pay_period.end < input.pay_period.start) {
      throw new EngineError("Invalid pay_period range");
    }
    payPeriod = [input.pay_period.start, input.pay_period.end];
  }
  if ((settings.max_days_window === "pay_period" || settings.weekly_hour_window === "pay_period") && payPeriod === null) {
    throw new EngineError(
      "pay_period window selected but no pay_period dates supplied"
    );
  }
  const history = (input.history ?? []).filter((h) => {
    if (!isValidDate(h.date)) {
      throw new EngineError(`Invalid history date: ${h.date}`);
    }
    return true;
  });
  return {
    settings,
    drivers,
    driverById,
    droppedDrivers,
    shifts,
    blackout,
    weekStartDay,
    scheduleWeek: [
      input.schedule_week_start,
      addDays(input.schedule_week_start, 6)
    ],
    payPeriod,
    history,
    patterns: /* @__PURE__ */ new Map(),
    adHoc: indexAdHoc(input.ad_hoc_constraints)
  };
}
function buildDriverTotals(ctx, ws) {
  const week = ctx.scheduleWeek;
  return ctx.drivers.map((driver) => {
    const state = ws.states.get(driver.driver_id);
    const assigned = state ? state.assigned : [];
    const ids = assigned.map((a) => a.shift_id).sort();
    const dates = [...new Set(assigned.map((a) => a.date))].sort();
    const work = state ? workHoursInWindow(state, week) : 0;
    const pto = ptoHoursInWindow(driver, week, ctx.settings);
    return {
      driver_id: driver.driver_id,
      assigned_shift_ids: ids,
      assigned_dates: dates,
      work_hours: work,
      pto_hours: pto,
      total_counted_hours: work + (ctx.settings.pto_counts_toward_cap ? pto : 0),
      max_days_used: state ? uniqueDatesInWindow(state, week).size : 0
    };
  });
}
function round1(n) {
  return Math.round(n * 10) / 10;
}
function runEngine(input) {
  const startedAt = Date.now();
  const ctx = buildContext(input);
  const plans = prepareSchedule(ctx);
  const states = initDriverState(ctx, plans);
  const planByShiftId = new Map(plans.map((p) => [p.shift.shift_id, p]));
  const ws = { plans, planByShiftId, states };
  const lockWarnings = applyDriverDayLocks(ctx, ws, input.ad_hoc_constraints ?? []);
  const matrix = buildEligibilityMatrix(ctx, ws);
  ctx.patterns = computePatterns(ctx);
  runPatternPass(ctx, ws, matrix);
  runMainPass(ctx, ws, matrix);
  const optimizationIterations = runOptimization(ctx, ws);
  runPreferredEnhancement(ctx, ws);
  runAffinityEnhancement(ctx, ws);
  const { violations, warnings } = validate(ctx, ws);
  warnings.push(...lockWarnings);
  if (ctx.settings.historical_pattern_protection !== "off") {
    const coldCount = ctx.drivers.filter(
      (d) => ctx.patterns.get(d.driver_id)?.cold_start
    ).length;
    if (coldCount > 0) {
      const windowWeeks = ctx.settings.history_window_weeks;
      warnings.push({
        type: "affinity_cold_start",
        message: `${coldCount} of ${ctx.drivers.length} drivers have schedule history in fewer than ${Math.ceil(windowWeeks / 2)} of the last ${windowWeeks} weeks \u2014 historical patterns are neutral for them this run (they'll kick in as more weeks accumulate)`
      });
    }
  }
  runFifthDayFill(ctx, ws);
  const assignmentExplanations = buildAssignmentExplanations(
    ctx,
    ws,
    warnings
  );
  const uncovered = buildUncovered(ctx, ws);
  const unscheduledDrivers = buildUnscheduledDrivers(ctx, ws);
  const assigned = [];
  let filled = 0;
  let closed = 0;
  let preservedPatternMatch = 0;
  let preferredMatch = 0;
  for (const plan of ws.plans) {
    if (plan.closed) closed += 1;
    if (plan.assignedDriverId === null || plan.source === null) continue;
    filled += 1;
    assigned.push({
      shift_id: plan.shift.shift_id,
      driver_id: plan.assignedDriverId,
      source: plan.source,
      total_score: plan.score ?? null,
      score_components: plan.scoreComponents ?? null
    });
    const pattern = ctx.patterns.get(plan.assignedDriverId);
    if (pattern && pattern.day_of_week_affinity[plan.shift.dow] >= 0.5) {
      preservedPatternMatch += 1;
    }
    const driver = ctx.driverById.get(plan.assignedDriverId);
    if (driver && inPreferredWindow(plan.shift, driver)) preferredMatch += 1;
  }
  assigned.sort(
    (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
  );
  const driverTotals = buildDriverTotals(ctx, ws);
  const driversScheduled = driverTotals.filter(
    (t) => t.assigned_shift_ids.length > 0
  );
  const totalWorkHours = driversScheduled.reduce(
    (sum, t) => sum + t.work_hours,
    0
  );
  violations.sort(
    (a, b) => (a.shift_id ?? "").localeCompare(b.shift_id ?? "") || a.rule.localeCompare(b.rule) || (a.driver_id ?? "").localeCompare(b.driver_id ?? "")
  );
  warnings.sort(
    (a, b) => a.type.localeCompare(b.type) || (a.shift_id ?? "").localeCompare(b.shift_id ?? "") || (a.driver_id ?? "").localeCompare(b.driver_id ?? "")
  );
  const uncoveredExplanations = uncovered.map((u) => ({
    shift_id: u.shift_id,
    decision: "uncovered",
    top_block_reasons: u.top_block_reasons,
    summary: u.summary
  }));
  const metrics = {
    engine_version: ENGINE_VERSION,
    total_shifts: ctx.shifts.length,
    filled_shifts: filled,
    uncovered_shifts: uncovered.length,
    closed_shifts: closed,
    drivers_scheduled: driversScheduled.length,
    avg_hours_per_scheduled_driver: driversScheduled.length === 0 ? 0 : round1(totalWorkHours / driversScheduled.length),
    drivers_near_weekly_cap: warnings.filter(
      (w) => w.type === "near_weekly_cap"
    ).length,
    drivers_near_max_days: warnings.filter((w) => w.type === "near_max_days").length,
    historical_pattern_preservation_pct: filled === 0 ? 0 : round1(preservedPatternMatch / filled * 100),
    preferred_availability_match_pct: filled === 0 ? 0 : round1(preferredMatch / filled * 100),
    attendance_risk_warnings_count: warnings.filter(
      (w) => w.type === "low_attendance_assigned"
    ).length,
    optimization_iterations: optimizationIterations,
    elapsed_ms: Date.now() - startedAt
  };
  return {
    assigned_shifts: assigned,
    uncovered_shifts: uncovered.map((u) => ({
      shift_id: u.shift_id,
      top_block_reasons: u.top_block_reasons,
      summary: u.summary
    })),
    driver_totals: driverTotals,
    violations,
    warnings,
    explanations: {
      assignments: assignmentExplanations.sort(
        (a, b) => a.shift_id < b.shift_id ? -1 : a.shift_id > b.shift_id ? 1 : 0
      ),
      uncovered: uncoveredExplanations
    },
    unscheduled_drivers: unscheduledDrivers,
    summary_metrics: metrics,
    inputs_hash: inputsHash(input)
  };
}

// src/adapters/dashboard.ts
var PTO_HOURS_PER_DAY = 10;
var ALL_DAY = [{ start: "00:00", end: "48:00" }];
function splitName(full) {
  const parts = full.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return { first: "Driver", last: "Driver" };
  if (parts.length === 1) return { first: parts[0], last: parts[0] };
  const last = parts[parts.length - 1];
  return { first: parts.slice(0, -1).join(" "), last };
}
function availabilityFromDows(dows) {
  if (dows == null) return null;
  const av = {};
  for (const dow of dows) {
    if (Number.isInteger(dow) && dow >= 0 && dow <= 6) {
      av[String(dow)] = ALL_DAY;
    }
  }
  return av;
}
function mapDriver(raw, ptoByDriver) {
  const status = String(raw.status ?? "").toLowerCase();
  const name = splitName(String(raw.full_name ?? raw.id));
  const emp = String(raw.employment_type ?? "").toLowerCase().replace(/[\s-]+/g, "_");
  return {
    driver_id: String(raw.id),
    first_name: name.first,
    last_name: name.last,
    status: status === "onboarding" ? "onboarding" : "active",
    employment_type: emp === "part_time" || emp === "parttime" || emp === "pt" ? "part_time" : "full_time",
    // A MISSING hire date must not make the driver the most senior (seniority
    // sorts ascending, so "2000-01-01" put unknown-tenure drivers at the front
    // of every priority queue — a data gap becoming top scheduling priority).
    // Default unknown tenure to a far-future date so they sort LEAST senior;
    // hire_date is only used for seniority ordering in the engine.
    hire_date: raw.hire_date && raw.hire_date.length >= 10 ? raw.hire_date.slice(0, 10) : "2999-12-31",
    license_expiration_date: raw.dl_expires_on ? raw.dl_expires_on.slice(0, 10) : null,
    dot_certified: raw.dot_certified === true,
    xl_certified: raw.xl_certified === true,
    saved_availability: availabilityFromDows(raw.available_dows),
    preferred_availability: availabilityFromDows(raw.preferred_dows),
    // No hours on the record → the engine applies the pto_default_hours
    // setting per day. Stamping a literal here (the old behavior) silently
    // overrode that setting for every DSP.
    pto_records: (ptoByDriver.get(String(raw.id)) ?? []).map((date) => ({
      date,
      hours: null
    })),
    attendance_score: null,
    attendance_final: raw.final_corrective_action === true,
    weekday_affinity: Array.isArray(raw.weekday_affinity) && raw.weekday_affinity.length === 7 ? raw.weekday_affinity : null,
    fifth_day_ok: raw.fifth_day_ok === true
  };
}
function toLocalWallClock(iso, tz) {
  if (!iso) return null;
  if (!tz || !/(?:[zZ]|[+-]\d{2}:?\d{2})$/.test(iso)) return iso;
  const t = new Date(iso);
  if (isNaN(t.getTime())) return iso;
  try {
    const parts = {};
    for (const p of new Intl.DateTimeFormat("en-CA", {
      timeZone: tz,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hour12: false
    }).formatToParts(t)) {
      parts[p.type] = p.value;
    }
    const hh = parts.hour === "24" ? "00" : parts.hour;
    return `${parts.year}-${parts.month}-${parts.day}T${hh}:${parts.minute}:${parts.second}`;
  } catch {
    return iso;
  }
}
function mapShift(raw, tz) {
  const startLocal = toLocalWallClock(raw.starts_at, tz);
  const endLocal = toLocalWallClock(raw.ends_at, tz);
  const start = startLocal ?? `${raw.date}T00:00:00`;
  const end = endLocal && startLocal && endLocal > startLocal ? endLocal : null;
  return {
    shift_id: String(raw.id),
    date: raw.date,
    start_time: start,
    end_time: end,
    duration_hours: typeof raw.duration_hours === "number" && raw.duration_hours > 0 ? raw.duration_hours : null,
    route_type: raw.route_type,
    assigned_driver_id: raw.assigned_driver_id ?? null,
    is_locked: raw.is_locked === true
  };
}
function clampMaxDays(value) {
  return Math.max(0, Math.min(7, Math.round(value ?? 6)));
}
function boundaryModeSettings(boundary, maxDays, assignmentMode, rotationBatch, enh, license, woc, affinity, fifthDayFill, fifthDayOverrideAvail, attendancePenalty, schedulingMethod, rotationStartDay) {
  return {
    run_mode: "full_rebuild",
    eligible_driver_status: "active_and_onboarding",
    // The license rule composes with the boundary modes — a driver with
    // an expired (or soon-to-expire) license is skipped, the rest of the
    // team fills normally.
    license_enforcement: license.on,
    license_protection_days: license.protectionDays,
    certification_enforcement: false,
    pto_protection: false,
    availability_enforcement: boundary === "availability",
    availability_required: boundary === "availability",
    max_days_enforcement: true,
    max_days: maxDays,
    // WOC composes with the boundary modes — a single Working Hours
    // Compliance rule capping consecutive days + weekly hours.
    weekly_hour_cap_enforcement: woc.on,
    weekly_hour_cap: woc.maxHours,
    pto_counts_toward_cap: false,
    min_rest_enforcement: false,
    woc_enforcement: woc.on,
    woc_max_consecutive_days: woc.maxConsecutiveDays,
    same_day_multi_shift: "block",
    historical_pattern_protection: "off",
    attendance_scheduling: false,
    attendance_penalty: attendancePenalty,
    scheduling_method: schedulingMethod,
    rotation_start_day: rotationStartDay,
    assignment_mode: assignmentMode,
    rotation_batch_size: rotationBatch,
    preferred_availability_priority: false,
    preferred_availability_required: boundary === "preferred",
    // The enhancement is a no-op under the preferred-only boundary
    // (every shift is already on a preferred day), so it's forced off
    // there.
    preferred_enhancement: boundary === "preferred" ? false : enh.on,
    preferred_enhancement_contiguous: enh.contiguous,
    preferred_enhancement_extra: enh.extra,
    // Driver Affinity Enhancement composes with both boundary modes.
    affinity_enhancement: affinity.on,
    affinity_day_order: affinity.dayOrder,
    fifth_day_fill: fifthDayFill,
    fifth_day_override_availability: fifthDayOverrideAvail,
    consecutive_working_days: false
  };
}
function buildSettings(payload) {
  const r = payload.rules ?? {};
  const maxDays = clampMaxDays(payload.max_days);
  const assignmentMode = r.spread_evenly === false ? "sequential_fill" : "rotational_fill";
  const rotationBatch = Math.max(1, Math.min(4, Math.round(r.rotation_batch ?? 1)));
  const enh = {
    on: r.preferred_enhancement === true,
    contiguous: r.preferred_enhancement_contiguous !== false,
    extra: r.preferred_enhancement_extra === true
  };
  const license = {
    on: r.dl_valid !== false,
    protectionDays: Math.max(0, Math.min(365, Math.round(r.dl_protection_days ?? 0)))
  };
  const woc = {
    on: r.woc !== false,
    maxConsecutiveDays: Math.max(1, Math.min(7, Math.round(r.woc_max_consecutive_days ?? 6))),
    maxHours: Math.max(1, Math.min(168, Math.round(r.woc_max_hours ?? payload.weekly_hour_cap ?? 40)))
  };
  const affinity = {
    on: r.affinity_enhancement === true,
    dayOrder: Array.isArray(r.affinity_day_order) ? r.affinity_day_order : void 0
  };
  const fifthDayFill = r.fifth_day_fill === true;
  const fifthDayOverrideAvail = r.fifth_day_override_availability === true;
  const attendancePenalty = r.attendance_penalty === true;
  const schedulingMethod = r.fill_priority === "random" ? "random" : "seniority";
  const rotationStartDay = Math.max(0, Math.min(6, Math.round(r.rotation_start_day ?? 0)));
  const runMode = r.run_mode === "fill_empty_only" || r.run_mode === "rebuild_unlocked" ? r.run_mode : "full_rebuild";
  const preserveLocked = r.preserve_locked_assignments !== false;
  const METHOD_SET = /* @__PURE__ */ new Set([
    "fair_rotation",
    "seniority",
    "full_time_priority",
    "availability_first",
    "alphabetical",
    "attendance_priority",
    "random"
  ]);
  const explicitMethod = typeof r.scheduling_method === "string" && METHOD_SET.has(r.scheduling_method) ? r.scheduling_method : null;
  const sameDay = r.same_day_multi_shift === "allow" ? "allow" : "block";
  const PATTERN_SET = /* @__PURE__ */ new Set(["off", "low", "medium", "high"]);
  const patternStrength = typeof r.historical_pattern_protection === "string" && PATTERN_SET.has(r.historical_pattern_protection) ? r.historical_pattern_protection : "off";
  const historyWeeks = r.history_window_weeks === 6 || r.history_window_weeks === 8 ? r.history_window_weeks : 4;
  const attendanceScheduling = r.attendance_scheduling === true;
  const ATT_WEIGHT_SET = /* @__PURE__ */ new Set(["low", "medium", "high"]);
  const attendanceWeight = typeof r.attendance_weight === "string" && ATT_WEIGHT_SET.has(r.attendance_weight) ? r.attendance_weight : "medium";
  const WINDOW_SET = /* @__PURE__ */ new Set(["schedule_week", "rolling_7_days"]);
  const maxDaysWindow = typeof r.max_days_window === "string" && WINDOW_SET.has(r.max_days_window) ? r.max_days_window : "schedule_week";
  const targetDays = Math.max(0, Math.min(
    7,
    Math.round(r.target_days_per_week ?? 4)
  ));
  const weeklyHourWindow = typeof r.weekly_hour_window === "string" && WINDOW_SET.has(r.weekly_hour_window) ? r.weekly_hour_window : "schedule_week";
  const ptoCountsTowardCap = r.pto_counts_toward_cap !== false;
  const ptoDefaultHours = Math.max(0, Math.min(
    24,
    Math.round(r.pto_default_hours ?? PTO_HOURS_PER_DAY)
  ));
  const minRestHours = Math.max(0, Math.min(
    48,
    Math.round(r.min_rest_hours ?? 10)
  ));
  if (r.preferred_only === true) {
    return boundaryModeSettings("preferred", maxDays, assignmentMode, rotationBatch, enh, license, woc, affinity, fifthDayFill, fifthDayOverrideAvail, attendancePenalty, schedulingMethod, rotationStartDay);
  }
  if (r.availability_only === true) {
    return boundaryModeSettings("availability", maxDays, assignmentMode, rotationBatch, enh, license, woc, affinity, fifthDayFill, fifthDayOverrideAvail, attendancePenalty, schedulingMethod, rotationStartDay);
  }
  const legacyMethod = r.tiebreaker === "seniority" ? "seniority" : "fair_rotation";
  const finalMethod = explicitMethod ?? (schedulingMethod === "random" ? "random" : legacyMethod);
  return {
    run_mode: runMode,
    preserve_locked_assignments: preserveLocked,
    eligible_driver_status: r.include_onboarding !== false ? "active_and_onboarding" : "active_only",
    license_enforcement: license.on,
    license_protection_days: license.protectionDays,
    certification_enforcement: true,
    pto_protection: r.pto_block !== false,
    availability_enforcement: r.availability !== false,
    availability_required: false,
    max_days_enforcement: true,
    max_days: maxDays,
    max_days_window: maxDaysWindow,
    target_days_per_week: targetDays,
    // WOC (Working Hours Compliance) governs the weekly-hours cap.
    weekly_hour_cap_enforcement: woc.on,
    weekly_hour_cap: woc.maxHours,
    weekly_hour_window: weeklyHourWindow,
    pto_counts_toward_cap: ptoCountsTowardCap,
    pto_default_hours: ptoDefaultHours,
    min_rest_enforcement: r.min_rest !== false,
    min_rest_hours: minRestHours,
    // WOC — also caps consecutive working days.
    woc_enforcement: woc.on,
    woc_max_consecutive_days: woc.maxConsecutiveDays,
    same_day_multi_shift: sameDay,
    historical_pattern_protection: patternStrength,
    history_window_weeks: historyWeeks,
    attendance_scheduling: attendanceScheduling,
    attendance_penalty: attendancePenalty,
    attendance_weight: attendanceWeight,
    scheduling_method: finalMethod,
    assignment_mode: assignmentMode,
    rotation_batch_size: rotationBatch,
    rotation_start_day: rotationStartDay,
    preferred_availability_priority: r.preferred_days !== false,
    preferred_availability_required: r.preferred_availability_required === true,
    preferred_enhancement: enh.on,
    preferred_enhancement_contiguous: enh.contiguous,
    preferred_enhancement_extra: enh.extra,
    affinity_enhancement: affinity.on,
    affinity_day_order: affinity.dayOrder,
    fifth_day_fill: fifthDayFill,
    fifth_day_override_availability: fifthDayOverrideAvail,
    consecutive_working_days: r.consecutive_days === true
  };
}
function planScheduleWeek(payload) {
  if (!payload || typeof payload !== "object") {
    throw new EngineError("planScheduleWeek: payload required");
  }
  const ptoByDriver = /* @__PURE__ */ new Map();
  for (const p of payload.pto ?? []) {
    const list = ptoByDriver.get(p.driver_id) ?? [];
    list.push(p.date);
    ptoByDriver.set(p.driver_id, list);
  }
  const eligibleRaw = payload.drivers.filter((d) => {
    const s = String(d.status ?? "").toLowerCase();
    return s === "active" || s === "onboarding";
  });
  const drivers = eligibleRaw.map((d) => mapDriver(d, ptoByDriver));
  const settings = buildSettings(payload);
  const tz = typeof payload.dsp_timezone === "string" && payload.dsp_timezone ? payload.dsp_timezone : null;
  const input = {
    schedule_week_start: payload.schedule_week_start,
    shifts: payload.shifts.map((s) => mapShift(s, tz)),
    drivers,
    dsp: { dsp_blackout_dates: payload.blackout_dates ?? [] },
    settings,
    ad_hoc_constraints: payload.ad_hoc_constraints
  };
  const result = runEngine(input);
  if (settings.scheduling_method === "seniority") {
    for (const d of eligibleRaw) {
      if (d.hire_date && d.hire_date.length >= 10) continue;
      result.warnings.push({
        type: "hire_date_missing",
        driver_id: String(d.id),
        message: `${String(d.full_name ?? d.id)} has no hire date on file \u2014 ranked least-senior by the Seniority scheduling method until one is set`
      });
    }
  }
  return result;
}
export {
  ENGINE_VERSION,
  EngineError,
  planScheduleWeek,
  runEngine
};
