// RouteReady Dispatch · dashboard service worker
//
// ── RECOVERY MODE + FORCED REFRESH ───────────────────────────────
// A prior caching strategy poisoned some operators' browsers with a
// stale MIX of assets across rapid deploys. This worker caches NOTHING
// and PURGES every existing cache the moment it activates, so all
// requests go straight to the network (governed only by the HTTP cache
// headers in _headers — HTML = no-cache; JS/CSS = ?v= versioned).
//
// NEW (forced refresh): on activate we ALSO navigate every open window
// to a fresh copy. An INSTALLED app that's resumed (not cold-launched)
// can sit on a stale shell indefinitely — the no-cache headers never
// get a chance to run because the shell is never re-requested. By
// reloading controlled clients the moment a new worker takes over, a
// deploy reaches even a pinned installed app: the browser fetches the
// new sw.js on launch, this worker activates, wipes caches, and
// navigates the window to the current shell. No DevTools, no incognito,
// no "clear site data" required.
//
// Re-navigation only fires when a NEW worker activates (i.e. when this
// file's bytes change on a deploy), so it cannot loop: the reloaded
// page registers the same worker, finds no update, and nothing else
// fires.

// ── Deploy nonce ─────────────────────────────────────────────────
// Bump this on any CSS/HTML-only deploy that must reach pinned/installed
// apps. sw.js byte-changes are the ONLY trigger for the forced refresh
// below (new worker → activate → purge caches → navigate windows to the
// fresh shell), so a recolor that never touches sw.js can sit invisible
// on a resumed installed app. Bumping forces every open window to the
// current shell on next launch.
//   2026-06-28.10 · Roster: remove Coach-driver toolbar pill; per-row coach icon.
//   2026-06-28.11 · Driver drawer: move Driver's-license section from Credentials to Documents.
//   2026-06-28.12 · Roster: keep the per-row coach menu on-screen (clamp to viewport).
//   2026-06-28.13 · Roster: add a per-row Message-driver icon.
//   2026-06-28.14 · Roster: per-row ⋯ menu (deep-link to record tabs + actions).
//   2026-06-28.15 · Roster: ⋯ tab items open a compact peek popup (one tab, not the full record).
//   2026-06-28.16 · Roster: row click no longer opens the full driver record (use the ⋯ menu).
//   2026-06-28.17 · Schedule: slim right utility rail + slide-out Notes scratchpad.
//   2026-06-28.18 · Schedule: rail flush-top, bookmark icon, push-to-condense, blends with bg.
//   2026-06-28.19 · Schedule: rail shield toggles Operations Health (default hidden); old header toggle removed.
//   2026-06-28.20 · Schedule: rail drops to the grid top; reserve its width so right-edge cells aren't clipped.
//   2026-06-28.21 · Schedule: reliable rail/panel top-sync (grid top); notes panel uses the canvas bg.
//   2026-06-28.22 · Schedule: notes panel goes flat (drop the shadow).
//   2026-06-28.23 · Schedule: rail anchors to the day-header row (true grid top); notes panel bordered all sides.
//   2026-06-28.24 · Schedule: Scratchpad upgraded to a polished Notes & Tasks productivity rail (tabs, rich composer, tasks).
//   2026-06-28.25 · Schedule: split Notes & Tasks into two separate slide-out panels, each with its own rail icon.
//   2026-06-28.26 · Schedule: Google-Calendar-style rail interaction — icon press, yellow ripple, panel slide + content fade.
//   2026-06-28.27 · Schedule: fill in the rail icons (solid Notes bookmark + Tasks tile, matching the shield).
//   2026-06-28.28 · Schedule: anchor the right rail flush with the roster table head (was riding too high on the Roster sub-view).
//   2026-06-28.29 · Schedule: premium V2 polish pass — coverage status card, elevated shift chips + toolbar, softer today wash, calmer hierarchy.
//   2026-06-28.30 · Roster: search now promotes matches to the top (Matches / Other drivers) instead of filtering, so the page stays full.
//   2026-06-28.32 · App Launcher: add an "ADP Sync" item that opens a focused box to connect/sync the DSP with ADP (mock OAuth). (.31 Marketplace reverted.)
//   2026-06-28.33 · ADP Sync goes real: connect/sync via Finch (unified HR API) — finch-* edge functions + 0398 migration; box now talks to the server.
//   2026-06-28.34 · Forms quick-access tab: force pinned/installed apps to the new shell (the forms-tab deploy was HTML/CSS-only and never bumped sw.js, so resumed apps stayed on the pre-feature shell).
//   2026-06-28.35 · ADP Sync: surface Finch's real connect error in the toast (no more generic "not set up"); finch-oauth-start tries both session endpoints.
//   2026-06-28.36 · Force installed/resumed clients to fetch the bumped worker: register with updateViaCache:"none" + active reg.update() on load and on return-to-app, so a deploy reaches pinned apps that never cold-launch (forms tab was never appearing for these clients).
//   2026-06-28.37 · Forms: open the forms slide-out from a Forms icon on the Schedule right-side utility rail (beside Notes/Tasks/Operations Health) instead of a floating tab; the slide-out now lists the operator's REAL forms (live cache) rather than placeholder rows. Floating #rr-forms-tab removed.
//   2026-06-28.38 · Forms: render the Forms panel as the SAME compact rail push-panel as Notes/Tasks (matching width, simple "Forms" + X header, one-at-a-time behavior) instead of the wide full-height detail-drawer with the oversized header. Old #rr-forms-tool-drawer removed; rows restyled to match the Tasks list.
//   2026-06-28.39 · ADP Sync: "Create driver records" — import active ADP employees as onboarding drivers (review count + one-click), matched so existing drivers aren't duplicated.
//   2026-06-28.40 · Roster: restore the per-row phone ("See driver's app view") icon on the active-driver rows — opens the driver-app preview, beside Message/Coach/More; actions column widened for the 4th icon.
//   2026-06-28.41 · Forms: redesign the Schedule rail's Forms panel into a polished "Driver Forms" surface — header + subtitle + primary New Form button, search, trigger filter chips, clean white form cards with soft muted status/requirement badges + monochrome icons, and Showing 1–N pagination (understated Google-Workspace aesthetic; blue reserved for primary action + selected chip).
//   2026-06-28.42 · Form builder: enterprise refresh — collapsible/searchable toolbox with field cards, Build/Logic/Settings/Preview tabs, refined draggable field blocks (type/required badges + hover toolbar + duplicate), document-style header with category chips, accordion properties, live Driver-App preview (phone/tablet/desktop), premium empty state, bottom drop zone, status footer. Conditional logic is a deliberate follow-up.
//   2026-06-28.43 · Form builder V2-a: the Driver-App preview is now a PERMANENT ~320px column on the Build tab (4-column grid: toolbox · canvas · preview · properties; widened modal) with two-way canvas↔preview selection sync (click a preview row to select it; selected field rings in both panes) and Phone/Tablet/Portrait/Landscape device toggles. Properties panel restructured into 5 tabs (Field/Rules/Logic/Style/More). Added an "All changes saved / Unsaved changes" header indicator, plus Copy (copies field JSON to clipboard) and a conditional Logic badge on field blocks. The redundant Preview tab was removed; preview column collapses below ~1100px. Conditional logic ships in V2-b.
//   2026-06-28.44 · Form builder V2-b: conditional logic. The Logic tab is now a real editor — "Always show" vs "Show only if <earlier question> is/is not <value>", with a calm visual rule summary. The Logic badge on a block lights up for real, and the Driver-App preview annotates conditional fields ("Shown when … is Yes"). Stored as an optional field.condition jsonb (no migration). Driver App (app/) enforces it live: hidden conditional fields are not required and not submitted; revealed ones participate normally. (Driver runtime ships via the app/ SW shell-cache bump.)
//   2026-06-28.45 · Form builder: fix drag-and-drop. Reordering a field block now works again — dragging is driven from the ⋮⋮ handle only (the row is no longer draggable=true), so grabbing a disabled preview input, a toolbar button, or a badge can't start or swallow the drag. The toolbox now also supports drag-to-insert: drag a field-type card from the left palette into the canvas (onto a position, the bottom drop zone, or empty canvas) to insert a new field of that type. Click-to-add, the keyboard ▲▼ nudge, selection, and the live preview are unchanged.
//   2026-06-29.46 · Form builder: the Driver preview now renders inside a realistic phone mockup (titanium bezel, dynamic island, status bar) instead of a plain rectangular frame — reusing the marketing iPhone-frame chrome (terms.html/privacy.html), re-scoped as .bdev-* under the preview column. The live form scrolls inside the phone screen; canvas↔preview selection sync and the Phone/Tablet/Portrait/Landscape device toggle are unchanged.
//   2026-06-29.47 · Form builder: keep the Driver-preview phone mockup a FIXED height. Previously the phone grew taller as fields were added and overflowed the modal; now the device fills the preview column's available height (capped per device/orientation) and the form scrolls INSIDE the screen, with the status bar + dynamic island pinned at the top. CSS-only — preview content, selection sync, and the device toggle are unchanged.
//   2026-06-29.48 · Form builder: give the Driver-preview phone a FIXED phone SHAPE so it never looks stubby. The previous fix used flex:1 + max-height, so a short/empty form still shrank the device to its content — an empty "Nothing to preview yet" rendered a squat box. Now each device/orientation has DEFINITE dimensions (explicit width + height; phone portrait ~268×581, a tall ~9:19.5 phone), independent of field count, capped to the column; the .bdev-viewport is the only scroll area and the empty state is centered. Empty and full previews show the identical full-height phone. Tablet + Portrait/Landscape are each definite shapes too. CSS-only.
//   2026-06-29.49 · Form builder: replace the Driver-preview phone mockup with a PLAIN preview panel. The realistic iPhone chrome (titanium bezel, dynamic island, 9:41 status bar, side buttons) is gone; the live driver form now renders inside a clean bordered card (--surface panel, --border hairline, --r-xl radius, subtle shadow). Everything else is preserved: the permanent DRIVER PREVIEW column, the Phone/Tablet/Portrait/Landscape toggle (now resizing the plain panel), live updates, two-way selection sync, the conditional-logic annotation, and the fixed-height card with the form scrolling internally. CSS + markup-trim only.
//   2026-07-05.50 · Workbook: emails/URLs render as clickable hyperlinks; clicking an email opens the RouteReady composer (never Gmail). Force pinned/installed/resumed apps off the stale shell so the new workbook.js (link handling) actually loads — the workbook link work was JS-only and never bumped this nonce, so resumed apps kept the pre-feature bundle and still opened Gmail.
//   2026-07-06.51 · Schedule: add Callout Exposure to the Operations Health side panel. Per-day math — at-risk scheduled drivers (attendance score < 70) vs the cushion (scheduled drivers − required routes); a day is "exposed" only when at-risk drivers outnumber the cushion, otherwise "Covered by +N" / "Covered exactly". Panel shows the worst-day summary; click opens a by-day breakdown. Finalize warns (advisory, non-blocking) when any day is exposed. Grid/day-headers/shift-cards unchanged.
//   2026-07-06.52 · Callout Exposure: the "at-risk" driver is now the roster's High-Risk designation (an active final/termination corrective action), loaded in the schedule render so it's correct without opening the roster first — not the attendance score. Cushion math + panel + finalize warning unchanged.
//   2026-07-06.53 · Callout Exposure: narrow "High Risk" to exactly an active (unresolved) FINAL corrective action (drop termination) per operator definition.
//   2026-07-06.54 · Callout Exposure: recommend + apply a fix. The by-day drill-down now proposes a backup-coverage plan — for each exposed day it picks enough available, low-risk drivers (respecting availability, PTO, max-days) to bring the day back to covered, and an "Apply backups" button creates those shifts (copying the day's real station/wave times). Additive only; re-renders with the new cushion folded in.
//   2026-07-06.55 · Callout Exposure backups: always assign SP (standard parcel) — never inherit an XL/other route type from the day's first shift. Recommendation now honors the enforced Smart Fill rules too: DL valid through the shift date + weekly hour cap, on top of active/PTO/max-days/availability (certs are moot since backups are SP).
//   2026-07-06.56 · Workbook: email links (spreadsheet cells AND rich-text note blocks) now open the RouteReady composer instead of Gmail. Force pinned/installed/resumed apps to the new shell so the new workbook.js actually loads — otherwise a resumed app kept the old bundle and mailto: links still opened Gmail.
//   2026-07-06.57 · Callout Exposure backups: add the last two always-enforced WOC rules — max consecutive working days and min rest between shifts (from get_woc_settings; defaults 6 days / 10h). The recommender now honors every enforced Smart Fill hard gate.
//   2026-07-06.58 · Schedule: remove the Max/day row (Flex Capacity) from the Operations Health side panel, along with its "Max routes/day" drill-down modal and its Flex Capacity entry in the KPI selector. The flex-capacity engine bundle is no longer imported by the dashboard (the edge function is untouched).
//   2026-07-06.59 · Schedule rail: split the combined Checklists / My Tasks panel into two slide-outs, each with its own rail icon — the green check tile now opens Checklists directly, and a new violet circle-check (carrying the open-task badge) opens the personal My Tasks list. The in-panel segmented switcher is gone.
//   2026-07-07.60 · Messages: URLs in chat bodies render as clickable links (driver chat, channels, support threads, orientation chat — dashboard side matches the driver app), and Ctrl+V pastes an image from the clipboard straight into the direct-chat/channel composer as a pending attachment.
//   2026-07-07.61 · My Tasks → team tasks (migration 0432): the rail list is now server-backed (public.team_tasks) so it follows the account to any desktop, and a leader can assign tasks to other leadership via the new "Assign to" picker. My Tasks / Delegated view chips (with open counts), "from X" / "→ X" provenance pills, assignee avatars, realtime per-DSP sync with an in-app popup when a task is assigned to you (no email), one-time import of the old device-local list (backup kept), and a full localStorage fallback until the migration is applied.
//   2026-07-07.62 · My Tasks: tone down the new team-tasks accents per operator — the My Tasks / Delegated switcher becomes flat text tabs with a dark-slate underline on a hairline (no violet pills), "from X" / "→ X" provenance is plain muted text (no pill), and teammate avatars drop the violet tint. CSS-only.
//   2026-07-07.63 · Schedule rail → Driver Forms: the per-card ⋮ button now opens a real Edit / Delete menu (it was a visual-only stub that swallowed the click). Edit reuses the card's existing open-builder path; Delete confirms, calls the same delete_form RPC as the Forms workspace grid, drops the form from the shared live cache, and repaints the panel. Menu dismisses on outside click / Escape, and reuses the checklist panel's dropdown styling.
//   2026-07-07.64 · Team tasks × calendar (migration 0433): open tasks now render as quiet slate chips on their due date across the operations calendar (all-day lane in day/week views, above the pills in month cells, busy dots in year view), gated by a new "Tasks" row in My Calendars. Chips complete in place (small check), click through to the rail Tasks panel, and drag to another day to reschedule (team_task_set_due; works on the localStorage fallback too). The calendar Create → Task dialog gains the leadership "Assign to" picker (parity with the rail form), and tasks due today nudge once per day via the reminder tick (in-app toast + browser notification — no email).
//   2026-07-07.65 · Team tasks accountability (migration 0434): clicking a task opens a detail modal with an activity trail (created / assigned / due changed / completed / reopened / acknowledged, auto-logged by a DB trigger) interleaved with a per-task comment thread. Delegated tasks gain an "Acknowledge — I've got this" action for the assignee, an at-a-glance ✓/● ack indicator on rows, and a realtime in-app notice to the assigner when their task is acknowledged or commented on (no email). Falls back cleanly (rows non-clickable) until the migration is applied.
//   2026-07-07.66 · Team tasks unread messages (migration 0435): tasks with a comment now carry a 💬 count on the row, lit blue with a pip when there's a message you haven't seen, and the My Tasks rail icon shows a small blue unread dot — so a comment left while you were away is flagged persistently instead of only a transient toast. Opening a task marks it read (per-user), and the Delegated view doubles as a "did anyone reply?" inbox. Realtime comment now also refreshes the row badges. No email.
//   2026-07-07.67 · Workbook dashboard: tone down the loud accents per operator. The "Auto-build" / "Ask" / "Auto-build from my data" buttons and the Auto-Insights icon drop the violet→blue gradient and purple glow for a flat, on-brand accent blue; the hero KPI band softens from a tri-colour violet gradient to a quiet single-hue blue; and the AI ask-bar loses its purple-tinted shadow. CSS-only.
//   2026-07-07.68 · Workbook dashboard: drop the redundant "Build your dashboard" empty-state card. An empty dashboard now stays clean — the always-visible top bar (✨ Auto-build · ＋ Add widget) and the "Ask about your data" bar already offer every action the card duplicated.
//   2026-07-07.69 · AI-built dashboards read cleaner + more professional: the auto-build and "Ask" builders now render one restrained brand-blue scorecard system instead of an 8-hue rainbow — KPI numbers go ink (accent lives only in the sparkline + tile edge), charts drop the "vibrant" theme for the curated RouteReady palette, and the hero becomes a refined light header (surface + slim accent edge, ink title) rather than a heavy saturated blue slab.
//   2026-07-07.70 · Recruiting Calendar polish: event blocks now read by calendar/kind so the grid matches the "My calendars" legend — one --ev-hue drives a crisp colored left rail, soft fill, hairline and text (interviews blue, orientations amber, events teal, sessions purple), restoring the accent rail the earlier weight-reduction pass had flattened. Exception statuses keep their alarm colors (no-show red, declined/cancelled gray + strikethrough); pending RSVPs get a dashed rail (week/day) and a hollow ring dot (month). Weekend columns/headers/month cells get a whisper-quiet wash and the today column's blue is lifted. Applies across Week / Work Week / Day / Month / Agenda / all-day lane.
//   2026-07-07.71 · Receipt Ledger (Receipt Intake): the Status column now reliably renders as a colored dropdown — a client-side guard re-applies the data-validation rule to the ledger sheet whenever it's opened (any way), so a ledger created before the rule existed is fixed in place. Adds a "How it works" tab explaining the scanner → ledger → reconcile → delete flow, and a "Delete entry" action in the View Receipt modal. Bumps the nonce so the earlier workbook.js changes (View Receipt cell, template card, delete) actually ship past the service-worker cache.
//   2026-07-07.72 · Workbook template gallery: for now the "New workbook" gallery offers only the Receipt Ledger template (the other templates stay defined so existing workbooks keep their badges, they're just hidden from the picker). CSS/logic only.
//   2026-07-07.73 · Schedule week board "Direction A" maturity pass: the coverage floating card folds into the command bar as a slim inline meter (green/amber/red by state), the red "V" / gold "OT" row dots become quiet soft-fill chips, grid digits go tabular so columns align, and standard shift chips flatten to a hairline with a receded route code so the time leads. CSS in inline-styles.css + a small coverage-meter injection in live.js renderScheduleWeek.
//   2026-07-08.1 · DSP control center (platform admin): world-class redesign of the DSP Account Management view — KPI hero now carries live context lines (new-in-30d, % operating with a utilisation bar, oldest-pending age) plus a control-center band with a prioritised "Needs attention" queue (no-owner / pending-aging / zero-drivers / idle signals, click to focus a DSP) and a Portfolio snapshot (drivers under management + plan-mix bars). The table gains a health dot and a Modules column. New: per-DSP page + feature entitlements — an "Access & modules" drawer lets an admin turn top-level pages (Schedule, Onboarding, Fleet, Workbooks, Messages, Email, Recognition) and in-app features (Notes, Tasks, Checklists, Contacts, Ops Health, Forms, Kudos) on/off for a whole DSP; the dashboard hides the disabled nav items / feature buttons via an injected stylesheet. Backed by migration 0442 (admin_set_dsp_entitlements + admin_list_dsps now returns the entitlement lists).
//   2026-07-08.2 · Schedule week board accessibility: the driver grid now carries WAI-ARIA grid semantics (role=grid/row/columnheader/rowheader/gridcell + per-cell aria-labels), a single roving tabindex with Arrow/Home/End keyboard navigation across day cells, and a keyboard-only assign flow — focus an open-shift chip, press Enter to "pick it up", navigate to a driver-day cell, and press Enter to assign (Escape cancels). Actions are announced via an aria-live region. A keyboard/screen-reader operator can now schedule without a mouse; previously drag-and-drop was the only path. live.js (_rrA11yStampScheduleGrid + keyboard handler in bindSchedWeekNav) + schedule-rrx.css focus/carry styles.
//   2026-07-08.3 · DSP control center — data integrity + drill-down. Signals are now backed by real data: a true dsps.last_seen_at (bumped by touch_dsp_activity() on boot) replaces the newest-teammate-signup proxy behind idle/last-active; the Routes column shows real distinct scheduled route codes for the week instead of a hardcoded 0; and a per-DSP 7-day client-error count feeds a new attention signal + health dot. Clicking a DSP (row "View details" or an attention row) now opens a full profile drawer — usage tiles (drivers / users / routes / errors / last-active / plan), an entitlements summary, the latest support thread with unread count, and recent client errors — with Edit / Manage users / Access & modules / Suspend quick actions. Backed by migration 0443 (touch_dsp_activity, admin_list_dsps gains route_count/error_count_7d/real last-active, admin_dsp_detail gains the profile payload).
//   2026-07-08.4 · DSP control center — presentation polish. Accessibility parity on the three platform-admin drawers (Manage users / Access & modules / DSP profile): each now traps Tab focus while open (aria-modal), moves focus in on open, restores focus to the trigger on close, and saving entitlements announces via an aria-live region. Responsive pass: the 11-column DSP table drops lower-priority columns by width (Phone → Routes/Last-active → Owner/Email → Plan), the KPI hero reflows to 2-up then 1-up, and the profile drawer goes full-width with 2-up tiles on phones. CSS media queries in inline-styles.css + shared drawer focus-trap/announcer helpers in live.js.
//   2026-07-08.5 · Checklists: palette + theming polish for the flag-resolution and compliance-insights drawers — swap the raw #hex accents/reds to the canonical --accent / --red / --border-strong tokens so both drawers track the app theme instead of being hardcoded light, and raise their overlay z-index to the modal convention (9999). live.js (_clfOpenFlags/_clfLoadFlags/_clfOpenInsights/_clfLoadInsights) + view-schedule.frag flags badge.
//   2026-07-08.6 · Schedule conflict UX: the three manual-assign paths (drag a shift from the open pool onto a driver, materialize an OKAMI gap chip, move a chip between cells) no longer surface rule violations through a native browser confirm(). They now open an in-context "Rule violations" dialog (matching the Finalize violations dialog + the add-shift card's inline warnings) that names the driver + day, lists the specific hard-rule breaches, and offers Cancel / Assign anyway — focus defaults to Cancel and Escape cancels, so a reflexive Enter never silently overrides. live.js (_rrConfirmAssignOverride + _rrAssignCtx, replacing confirm() in assignShiftToDriverWithRules / materializeVirtualShiftToDriver / the drag-move handler).
//   2026-07-08.7 · Checklists: remove the flag-resolution queue + compliance-insights drawers (buttons/drawers/handlers) from the Checklists rail; realtime flag-alert toast + Responses-tab flag markers kept. live.js + view-schedule.frag; backend objects dropped in migration 0444.
//   2026-07-08.8 · Schedule week board: fix the right edge of the grid being cut off. The recessed-tray .builder-shell used a symmetric margin:-6px/padding:6px full-bleed, but on the right it butts against the utility rail with no page padding to absorb the -6px — so the tray overran its container by 6px and the parent's overflow:hidden sheared the grid card's right edge / rounded corner. Bleed top/bottom/left only (margin:-6px 0 -6px -6px; padding:6px 0 6px 6px); the grid (.cal-wrap) stays in the exact same place. schedule-rrx.css only.
//   2026-07-08.9 · Launch-audit trust pass: the schedule week view no longer ships its static sample grid (fake drivers/coverage) — a skeleton renders until real data paints; three unreachable mockup sub-views (By-driver / Availability matrix / 4-week forecast) removed; the four not-yet-wired Intelligence tiles (Compliance watch / Hiring pulse / Peak days / What-if) are disabled with "coming soon" titles instead of opening a blank pane; Checklists header drops its hardcoded "14 active · 4 due now" counts; the roster "At risk" chip now filters on the real corrective-action signal (drivers.score is never computed — the old filter always returned an empty list) and the dead Score filter/column go away; onboarding-ops loses its five dead "Rules" stub buttons; the hired-card "Open onboarding" CTA actually opens Onboarding; the workbook data chip reads "Synced" (it's a snapshot, not live); EDV routes now work in the in-browser engine (parity with CP-SAT). Boot no longer invokes the mock staffing/pipeline painters.
//   2026-07-08.10 · Receipts panel: new rail slide-out (receipt icon between Forms and Recognition) that finally surfaces driver-submitted receipts to managers — the receipts_list / receipts_summary / receipt_set_status / receipt_resync RPCs (migration 0437) were built but had no UI. Filter chips (All / Needs review / Unreconciled / Duplicates), a quiet count·total summary, per-receipt detail modal with a signed-URL image preview + status/notes editing (ledger row syncs via the 0436 trigger), retry for failed ledger projections, and an "Open ledger" deep-link into the Receipt Ledger workbook (new window.rrOpenReceiptLedger hook in workbook.js). Gated per-DSP via the entitlements catalog (key: receipts). view-schedule.frag + live.js + schedule-rrx.css.
//   2026-07-08.11 · Schedule route colors, crispness pass (operator: "sharp, clear and crisp — even small differences matter"). Chips now paint EXACTLY the picked color (the 8% white color-mix wash is gone), the border is a solid same-hue edge pulled toward slate-900 (was a translucent/slate-400 mix), and chip text auto-contrasts per route (new --rr-route-t-* vars from the popover JS: white on dark picks, ink on light — also fixes the retired violet/pink legacy types that forced dark-on-dark). The Schedule Colors popover gains a second BOLD swatch row per route: the same 10 hues at full saturation (Tailwind-600 family the dashboard already uses) for operators who want vivid, unmistakable coding. schedule-rrx.css + view-schedule.frag; defaults unchanged, so nothing shifts until a bold color is picked.
//   2026-07-08.12 · Smart Fill now shows its work: a post-run "solve summary" card surfaces the CP-SAT optimizer's own signals — "Solved to optimality" (from the solver's OPTIMAL status), scale + solve time ("Optimized 218 routes across 47 drivers in 0.9s — every legal assignment evaluated"), coverage, and the rules it held (0 violations, as green-check chips) — so Smart Fill reads as the optimization engine it is instead of a silent grid fill. Built only from the real SolveResponse (metrics.solver_status / solver_wall_ms) + the enforced rules; dismissible; "See the decision report" opens the existing trace diagnostics. live.js (_rrShowSmartFillSummary + summary returned from autoFillScheduleWeek, shown from openAiSchedule).
//   2026-07-08.13 · Targets gap card grows a prescription: under the "−N Drivers" number it now says what to do about it — "Hire N by {hire-by}" (N = deepest weekly shortfall, date = the first short week's hire-by, so hiring by the earliest deadline covers every later break) or "Staffed through the plan" when covered. The card also now reads through _rrReadOkamiWeeks, so after "Simulate 13 weeks" it reflects the PTO-adjusted projection instead of the static plan, and a short plan makes the card clickable (mouse + keyboard) straight into the Risk forecast analysis. view-schedule.frag + live.js + inline-styles.css.
//   2026-07-08.14 · Two dispatchers, one schedule — no more silent overwrites. assign_shift (migration 0446) gains an optimistic expectation: every manual assign, undo, Smart Fill write-back, prev-week fill, and new-hire staging now says which driver it BELIEVES holds the shift, and the write refuses ('shift_conflict') instead of clobbering when a colleague changed it first — the UI explains and refreshes the board. And the long-dormant realtime subscriptions on shifts / shift_offers / driver_checkins finally fire: 0446 adds those tables to the supabase_realtime publication, so the week grid, Open Shifts rail, and Today's Plan repaint within ~1s of another dispatcher's change (the debounce + local-echo suppression were already built). live.js + migration 0446.
//   2026-07-08.15 · Workbook cell right-click: the "Delete cells" submenu now actually deletes cells. Previously it only offered Clear contents / Clear formatting (which leave the cell in place); it now leads with "Delete cells and shift up" and "Delete cells and shift left" — the Google Sheets behaviour that removes the selected cells (contents + formatting) and pulls the remaining cells in each affected column/row back over the gap, within the selected band only. New deleteCellsShift(g, dir) in workbook.js wired into both cell-menu handler switches; Clear contents / Clear formatting kept below a divider.
//   2026-07-08.16 · HOTFIX (regression from .12): Smart Fill wrote the shifts but the grid didn't repaint until you navigated away and back. The post-run solve-summary card's builder referenced sfPayload / _maxDaysOut, which are block-scoped inside autoAssignDriversForWeek and out of scope at that point → a ReferenceError threw out of autoAssignDriversForWeek → autoFillScheduleWeek never reached its post-write renderScheduleWeek(). The shifts were already saved (hence they showed on next navigation). Fix: build the recap from window._rrLastSmartFillPayload + function-scoped result/engineShifts/assigned, fully wrapped in try/catch so a broken recap can NEVER stop the render; hoist `summary` to function scope so the post-render card display resolves it; and show the card from inside autoFillScheduleWeek instead of a return value it never provided. live.js only.
//   2026-07-08.19 · Auto-build dashboards read cleaner. Three quality fixes in autoBuildDashboard (workbook.js): (1) KPI tiles now rank each sheet's numeric columns by real signal (non-zero total or >1 distinct value) before picking headline/secondary metrics, so dead "0" tiles like Worked=0 give way to a metric that actually moves; (2) sparklines are drawn only when a column has ≥3 non-null values with variation, killing the one-blip square-wave sparks on sparse columns; (3) charts are emitted only when they render legibly — a date dimension → a line over time, a categorical dimension only when it's low-cardinality (≤12 distinct) over ≤26 rows, otherwise no chart (a broken 66-bar smear was worse than none) — and series are capped at 4 (was up to 10) so the legend stays clean. workbook.js only.
//   2026-07-08.20 · Reports: forms become reportable. The Reports builder gains a "Forms" category — pick any of your forms and its submissions turn into a report (one row per submission, one column per field) with the same Download CSV / Print / Open in Workbook + Live-refresh options as People/Schedule/Attendance. Columns are built dynamically from the chosen form's fields (section headers / dividers / instructions excluded); driver + submitted-at + review status/flag/notes are fixed columns; signatures/photos/GPS/files collapse to readable text. Live report workbooks rebuild their catalog from get_form so they refresh even in a fresh session. reports.js only (RB_CATEGORIES + a dynamic "forms" source, fetchFormsList/fetchFormSubmissionsData, formsCatalogFrom, buildReportData forms branch, form-picker UI).
//   2026-07-08.21 · My Tasks recurrence gains a "Repeat forever" option — a no-end-date checkbox on the count row (hides the "for N occurrences" controls when on). Materialized-occurrence model has no rule-based top-up and the store caps a series at 60, so forever lays down the longest rolling horizon it can (60 occurrences) across whatever cadence is picked. view-schedule.frag + live.js + schedule-rrx.css.
//   2026-07-08.22 · "Repeat forever" tasks now auto-extend instead of running dry at the 60-occurrence seed. Forever series carry their recurrence rule in meta.recur (cadence + weekday/monthly pattern), and a daily pg_cron sweep (migration 0448) keeps each series topped up to a rolling buffer of ~40 future occurrences (refills when it drops below 20), resuming dormant series in the future with the weekday/day-of-month phase preserved. Count-limited repeats never set meta.recur, so the sweep skips them. live.js (recur rule on create) + migration 0448.
//   2026-07-08.23 · Workbook widget dialogs (Add table / KPI / chart): range fields get a "select on the grid" button so you no longer have to hand-type A1:K67. Clicking it drops the dialog out of the way, lets you drag across cells — and switch sheets via the tabs — with a floating bar showing the live range (Sheet!A1:K67) and Use-this-range / Cancel; Escape cancels, Enter confirms. Cross-sheet picks update the dialog's Data-source select; the dialog always returns to the sheet it was opened on so the widget still saves there. New wbRangeField/wireRangePick/beginRangePick+bar in workbook.js, hooked off paintSelection; styles in inline-styles.css.
//   2026-07-08.24 · Dashboard lockout escape hatch. Operators wedged on a stale app shell (an old service worker / Cache-Storage entries pointing at ?v= assets that no longer resolve) sat forever on the "We couldn't load your data" card — a view partial 404'd and boot aborted before __RR_BOOT_OK, and the card's only real action ("Try again") was a plain reload that re-served the same stale shell. Three fixes in index.html: (1) a shared window.__rrPurgeAndReload() that unregisters every SW AND deletes every Cache-Storage bucket, then hard-reloads uncontrolled with a cache-buster (self-timeout so a hung purge can't strand the operator); (2) the one-time auto-reset is re-armed (bumped key rr-sw-reset-20260708-dashlockout) and now purges Cache Storage too, not just SW registrations, so wedged clients self-heal on next load; (3) a "Reset app" button on the failure card plus an on-screen boot-error breadcrumb (window.__RR_BOOT_ERR) so the generic "connection hiccup" becomes an actionable detail line. index.html + inline-styles.css.
//   2026-07-08.25 · Workbook widget dialogs: switching the Data-source (sheet) dropdown now auto-fills the range field to that sheet's populated extent, so moving between sheets no longer leaves a stale range (e.g. A1:C66 from the old sheet). Only overwrites a range the user hasn't hand-edited — a range still holding the previous sheet's auto default gets refreshed; a deliberately typed one is left alone. New wireSrcAutoRange() in workbook.js wired into the chart / KPI / table dialogs.
//   2026-07-09.1 · Workbook reports: form photos render inline (PR #3627) and gain a right-click "Resize photos" tool with Small/Medium/Large/Extra-large presets + custom size (PR #3628). Both shipped as JS-only workbook.js/reports.js changes and never bumped this nonce, so pinned/installed/resumed apps kept the pre-feature bundle — photos still showed as "image.jpg" and the resize menu never appeared. Bumping forces every open window to the fresh shell so both features actually load.
//   2026-07-09.2 · Schedule enterprise polish pass. A visual-maturity re-skin of the Schedule dashboard toward a production logistics look: dark Amazon-style left rail (deep blue-black gradient, icon-over-label nav, bright-blue active accent bar), non-colorful app launcher/logo (monoline mark on a dark tile; the warm-yellow launcher button + colorful app-icon retired), darker top tabs with a blue active underline and a hairline divider under the whole row, a standardized 40px toolbar button system (white fill, #D7DEE8 hairline, 8px radius), an orange Finalize primary with a lock glyph (was blue), a compact coverage stat, a plain slate right utility rail (per-tile blue/violet/green/gold/indigo/teal/pink hues retired; blue only on the open panel), a subtle red-outline "V" van badge (was a solid red disc), and restrained light-blue shift cards (#F3F8FF + #CEDBEA hairline). CSS/markup only — inline-styles.css, schedule-rrx.css, index.html.
//   2026-07-09.3 · Desktop (window-controls-overlay) title bar: the segment above the dark left rail now paints the rail navy instead of light rail-blue, so the sidebar reads as reaching the very top of the window. Two-tone band with a hard colour stop at the rail width (84px collapsed / 176px expanded); the content-side segment stays light. inline-styles.css only.
//   2026-07-09.4 · HOTFIX — workbook cell right-click submenus (Resize photos, Paste special, Insert cells, Delete cells, View more cell actions) opened and instantly closed, so "Resize photos" never showed its size options. Drilling into a submenu re-renders the menu's innerHTML, detaching the clicked node; the document-level "click outside a popover closes it" handler then saw a target with no .wb-ctx-menu ancestor and wrongly closed the whole menu. Fixed by stopping propagation on clicks inside the cell menu. workbook.js only — nonce bump so installed/resumed apps get the fix.
//   2026-07-09.5 · Receipts panel: reconcile from the panel. Each still-open receipt card (Unreconciled / Needs Review / Duplicate Possible) gains an inline "Reconcile" action that marks it Matched in one click via the same receipt_set_status RPC the detail modal uses — the 0436 trigger mirrors it into the Receipt Ledger. Already-resolved receipts (Matched / Reimbursable) show no button; the detail modal still owns Reject / Reimbursable / notes. live.js + schedule-rrx.css.
//   2026-07-09.6 · Installed PWA (e.g. ChromeOS) title bar: theme-color → dark rail navy (#071E2F). In plain standalone display mode there is no window-controls-overlay band, so Chrome paints the whole window title bar from theme-color; it was light rail-blue, so the dark sidebar appeared to start below the top of the window. Navy theme-color makes the title bar dark (Chrome auto-lightens the min/max/close glyphs), so the rail reads as reaching the very top. manifest.webmanifest + index.html <meta theme-color>.
//   2026-07-09.7 · Receipts panel: close the dead space under the header. The filter toolbar (All / Needs review / Unreconciled / Duplicates chips + summary) defaults to opacity:0 and each panel re-reveals it via its own #id.is-open rule; Receipts was missing that rule, so the chips stayed invisible while still occupying ~113px — an empty band that pushed the first receipt far below the header. Added the receipts reveal rule so the toolbar shows and the list sits right under the header. schedule-rrx.css only.
//   2026-07-09.8 · Workbook report photos load fast at scale. A report can carry hundreds of photos; the grid is virtualized, so only on-screen photo cells now sign + fetch (lazy, per-viewport, concurrency-capped) instead of signing the whole sheet up front, and each thumbnail is served DOWNSCALED via Supabase image transforms (~640px, ~20KB) rather than the full ~1600px upload (~300KB) — a ~15× bytes cut — with loading=lazy + decoding=async. Click-to-enlarge signs a full-resolution URL on demand. If the storage tier can't transform, the first thumbnail 404s and we fall back to full-size URLs for the rest. workbook.js only.
//   2026-07-09.9 · Revert the full-width dark title bar (#3635 / nonce .6). Making theme-color navy turned the WHOLE standalone title bar dark, not just the sidebar column — a heavy full-width band. The sidebar-only-dark look is a two-tone effect that only works in Window Controls Overlay mode (body::before paints navy over the rail width, light over the content); standalone mode has one solid OS title bar, so theme-color goes back to light rail-blue (#EFF6FF) for a calm band there. WCO windows keep the sidebar-only navy. index.html <meta theme-color> + manifest.webmanifest theme_color (manifest ?v= bumped).
//   2026-07-09.10 · Workbook report photos: load the small thumbnail the driver app now uploads alongside each photo (answers[fid].thumb) instead of the full image — light loads on any Supabase tier (no server-side image transform, which is Pro-only). Photos with no thumbnail (older submissions, or a failed thumb upload) fall back to the full image; click-to-enlarge always signs the full-resolution URL; a missing thumbnail's <img> error swaps in the full image. Replaces the earlier transform-based approach. workbook.js + reports.js.
//   2026-07-09.11 · Schedule right utility rail: uniform filled icons. The last three rail buttons (Forms, Receipts, Recognition) were outline glyphs while the first five (Notes, My Tasks, Checklists, Contacts, Operations Health) were filled — a mismatched set. Redrew the three as filled glyphs (solid currentColor shape + white interior mark, matching the Checklists/Ops-Health style) so the whole rail reads as one system. view-schedule.frag only.
//   2026-07-09.12 · Messages quality pass. (1) The Conversations search box is now wired — it filters the Drivers / HR / Broadcasts lists in place (name + preview substring) and survives the 8s poll rebuilds, with a "no matches" note. (2) The channel/HR composer gained the same optimistic-send + click-to-retry + draft-preservation as 1:1 chat. (3) Optimistic-stub reconciliation is now count-aware, time-gated and attachment-aware, so duplicate or attachment-only sends no longer ghost or drop a bubble. (4) "Load earlier messages" grows the thread page 200→500→1000 (direct) / 200→500 (channels) with scroll preserved. (5) Failed sends now delete the just-uploaded attachment blob instead of orphaning it. (6) a11y: priority buttons are real role=radio/aria-checked radios, thread panes are labelled regions, icon buttons have aria-labels. live.js + view-messages.frag only.
//   2026-07-09.13 · Operator wants the ENTIRE title bar to match the dark sidebar (the two-tone left the top-right, over the content + behind the window controls, light). So the whole top bar goes dark: the WCO band (body::before) paints navy edge-to-edge instead of navy-over-rail-only, and theme-color goes back to the rail navy (#071E2F) so the window-controls corner is navy with light glyphs (and standalone shows the same full-width dark bar). Supersedes the #3638 light-band choice per operator request. inline-styles.css + index.html <meta theme-color> + manifest.webmanifest.
//   2026-07-09.14 · Title bar → TWO-TONE (operator clarified): the dark sidebar extends to the top over the rail column, and a LIGHT band runs across the rest of the top (over the content + behind the window controls). Reverts the .13 full-width dark bar: the WCO band (body::before) paints navy only over the rail width and light rail-blue over the content again, and theme-color goes back to light (#EFF6FF) so the window-controls corner joins the light band. inline-styles.css + index.html <meta theme-color> + manifest.webmanifest.
//   2026-07-09.15 · Messages search now searches full message HISTORY, not just the conversation list. On the Drivers tab a query of ≥2 chars runs a server full-text search (dispatch_chat_search RPC + pg_trgm index, migration 0449) across every driver message body in the DSP — so you can find a conversation by anything ever said in it, including drivers not in the loaded inbox — and shows matches with a snippet. HR/Broadcasts and 1-char queries keep the instant client-side name+preview filter. live.js only (server: migration 0449).
//   2026-07-09.16 · Message search: clicking a result now jumps to the matched message. A search hit opens the thread AND scrolls to the exact matched bubble (fetching the max page so an old message is loaded), flashing a ring around it, instead of dumping the operator at the bottom. dispatch_chat_search now returns the matched message id (migration 0450). live.js only (server: migration 0450).
//   2026-07-10.1 · Workbook: right-click a floating widget (chart / KPI / table / text / filter / insights tile) to get its own Edit · Duplicate · Delete menu instead of the browser's native context menu. Mirrors the header action buttons, reuses the shared cell-menu styling, and is edit-gated (read-only viewers keep the native menu). workbook.js only.
//   2026-07-10.2 · Workbook: drag-select now edge-auto-scrolls. Dragging a cell selection, a fill-handle, a column/row-header selection, or a cell move toward (or past) an edge of the grid keeps the sheet scrolling in that direction — and, crucially, keeps scrolling while the cursor is held still at the edge (the loop runs on requestAnimationFrame, not off mousemove), so you can extend a selection well beyond what's on screen without inching the mouse. Speed ramps with proximity to the edge. Supersedes the old mousemove-only nudge on cell moves. workbook.js only.
//   2026-07-10.3 · Title bar → solid dark again (operator: restore the dark top that worked before). theme-color back to the rail navy (#071E2F) so the installed PWA's standalone title bar is dark and the sidebar reads as reaching the top; the WCO band (body::before) is also solid navy edge-to-edge. Reverts the two-tone/light experiment. inline-styles.css + index.html <meta theme-color> + manifest.webmanifest.
//   2026-07-10.4 · Overlay title bar → TWO-TONE (operator wants dark over the sidebar, light over the rest). The body::before band paints navy over the rail width and light rail-blue over the content again — this renders in overlay-mode windows (the desktop app), which draw their own title bar. theme-color stays navy: a standalone PWA can't split the title bar (one OS-painted color), so it stays dark so the sidebar still reaches the top. inline-styles.css only.
//   2026-07-10.5 · Workbook data-viz depth. Pivot tables gain a "show values as" mode (% of total / running total / rank) + "Top N rows"; every value cell drills to the source rows behind it; two-level pivots collapse/expand; and "Chart this pivot" draws a live chart from the pivot output. Charts add a moving-average overlay + a target/reference line. Excel export now writes native chart parts and materializes each pivot as its own values sheet (was: silently dropped). Pivot cards show their active state as shared status pills. workbook.js + inline-styles.css.
//   2026-07-10.6 · Installed PWA title bar → light (operator: no dark top on the app). theme-color back to light rail-blue (#EFF6FF) so the standalone installed app's one-color title bar is light, not dark. The overlay band (body::before) stays two-tone (navy over the sidebar, light over the content) for the desktop app, which draws its own title bar. index.html <meta theme-color> + manifest.webmanifest.
//   2026-07-10.7 · Schedule toolbar → enterprise visual language. The playful bits are gone: the week navigator is now a white segmented control (36px, 6px radius, hairline dividers, light-gray hover, a blue OUTLINE on the active this-week segment instead of the old light-blue arrow fill); "Smart Fill" is renamed "Build Schedule" with a monochrome schedule glyph and the exact chrome of every other command button (no navy 1.5px outline, no brand-blue sparkle, no blue hover); the whole .rr-ab-btn system tightens 40px/8px → 36px/6px with a blue focus ring; toolbar hairlines darken to #D7DCE3; and schedule shift cards shift from baby-blue (#EFF6FF) to a cooler enterprise gray (#EEF2F6) with a #D6DDE6 hairline, lighter route weight, and no hover lift. schedule-rrx.css + inline-styles.css + view-schedule.frag.
//   2026-07-10.8 · Workbook pivot tables: heatmap cell highlighting. The pivot dialog gains a "Heatmap value cells" option (matching the dashboard table widget) that tints each value cell on a light blue min→max ramp, scaled per measure. Grand-total rows/columns are excluded from the scale and left untinted so totals don't wash it out; tinted cells pin dark ink for contrast in either theme. workbook.js + inline-styles.css only.
//   2026-07-10.9 · Workbook: pivot tables now render as floating grid embeds (like charts/KPIs/tables) — movable, resizable, on the sheet — instead of a strip below the grid. "pivots" became a first-class embed kind; collapse/chart toggles + state pills in a slim body toolbar; "Pivot table" added to the ＋ Add widget menu; dashboard pivots source a data sheet. workbook.js + inline-styles.css.
//   2026-07-10.10 · Workbook pivot dialog: the Source range field gets the "select on the grid" picker (grid icon → drag a range → Use this range), matching the chart/KPI/table dialogs, instead of typing a range by hand. Committing a pick now fires a change event so the pivot's field dropdowns reload from the picked range. workbook.js only.
const SW_DEPLOY_NONCE = "2026-07-10.10";

self.addEventListener("install", () => {
  // Take over as soon as possible so the purge + refresh run without
  // waiting for every dashboard tab to close.
  try { console.log("[rr-sw] installing build", SW_DEPLOY_NONCE); } catch (e) {}
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
      .then(() => self.clients.matchAll({ type: "window", includeUncontrolled: true }))
      .then((clients) => {
        clients.forEach((client) => {
          // Reload each open window to the fresh shell. Best-effort —
          // one client that refuses to navigate can't abort the rest.
          try { client.navigate(client.url); } catch (e) { /* ignore */ }
        });
      }),
  );
});

// No fetch handler that responds from cache. Without respondWith the
// browser performs its default network fetch, so nothing is served
// from a Service-Worker cache. (We don't register a fetch listener at
// all — pure pass-through.)

self.addEventListener("message", (event) => {
  const data = event.data || {};
  if (data.type === "rr:skip-waiting") self.skipWaiting();
});
