-- ─────────────────────────────────────────────────────────────────────────
-- Migration 0052 · Driver invite codes + sessions for the PWA
--
-- Drivers don't have auth.users accounts. They authenticate with a
-- short invite code generated by dispatch at orientation. Redeeming
-- the code returns a long-lived bearer token stored in driver_sessions.
-- Every driver-facing RPC takes that token as its first argument and
-- looks up the driver_id from driver_sessions, scoping the query.
--
-- Codes are single-use and auto-expire 14 days from issue. Issuing a
-- new code for a driver invalidates any existing un-consumed code
-- (one active code per driver at a time). Sessions never expire on a
-- timer — they're revoked when the dispatcher terminates the driver
-- or explicitly revokes the session, and validated on every call.
-- ─────────────────────────────────────────────────────────────────────────


-- ── 1. Tables ──
create table if not exists public.driver_invite_codes (
  code         text primary key,
  dsp_id       uuid not null references public.dsps(id) on delete cascade,
  driver_id    uuid not null references public.drivers(id) on delete cascade,
  created_by   uuid references auth.users(id),
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null default now() + interval '14 days',
  consumed_at  timestamptz
);
create index if not exists driver_invite_codes_driver_idx on public.driver_invite_codes(driver_id);
create index if not exists driver_invite_codes_active_idx on public.driver_invite_codes(driver_id) where consumed_at is null;

create table if not exists public.driver_sessions (
  token        text primary key,
  dsp_id       uuid not null references public.dsps(id) on delete cascade,
  driver_id    uuid not null references public.drivers(id) on delete cascade,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at   timestamptz,
  user_agent   text
);
create index if not exists driver_sessions_driver_idx on public.driver_sessions(driver_id);

alter table public.driver_invite_codes enable row level security;
alter table public.driver_sessions     enable row level security;

-- Tenant-scoped read for staff. No driver-side RLS needed because
-- driver-facing RPCs are SECURITY DEFINER and validate the token
-- internally; no anon SELECT/INSERT is granted directly.
drop policy if exists "driver_invite_codes_tenant_r" on public.driver_invite_codes;
create policy "driver_invite_codes_tenant_r"
  on public.driver_invite_codes for select
  using (dsp_id = private.current_dsp_id());

drop policy if exists "driver_sessions_tenant_r" on public.driver_sessions;
create policy "driver_sessions_tenant_r"
  on public.driver_sessions for select
  using (dsp_id = private.current_dsp_id());

grant select on public.driver_invite_codes to authenticated;
grant select on public.driver_sessions     to authenticated;


-- ── 2. issue_driver_invite — dispatcher-only ──
-- Generates an 8-character code (uppercase, no ambiguous chars), revokes
-- any prior un-consumed code for this driver, returns the new code.
create or replace function public.issue_driver_invite(p_driver_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_dsp uuid := private.current_dsp_id();
  v_code text;
  v_alphabet text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';  -- no 0/O/1/I/L
  v_collision boolean;
  v_attempts int := 0;
begin
  if not private.is_staff(v_dsp, 'dispatcher') then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  -- Verify driver belongs to this DSP.
  perform 1 from public.drivers where id = p_driver_id and dsp_id = v_dsp;
  if not found then
    raise exception 'driver_not_found' using errcode = 'P0002';
  end if;

  -- Generate unique 8-char code from the unambiguous alphabet.
  loop
    v_code := '';
    for i in 1..8 loop
      v_code := v_code || substr(v_alphabet, 1 + floor(random() * length(v_alphabet))::int, 1);
    end loop;
    select exists(select 1 from public.driver_invite_codes where code = v_code) into v_collision;
    v_attempts := v_attempts + 1;
    exit when not v_collision or v_attempts > 8;
  end loop;
  if v_collision then
    raise exception 'code_generation_failed';
  end if;

  -- Revoke any existing un-consumed code for this driver. One active at a time.
  update public.driver_invite_codes
     set expires_at = now()
   where driver_id = p_driver_id
     and consumed_at is null
     and expires_at > now();

  insert into public.driver_invite_codes (code, dsp_id, driver_id, created_by)
  values (v_code, v_dsp, p_driver_id, auth.uid());

  return v_code;
end;
$$;
grant execute on function public.issue_driver_invite(uuid) to authenticated;


-- ── 3. redeem_driver_invite — anon-callable, returns session ──
create or replace function public.redeem_driver_invite(p_code text, p_user_agent text default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_invite public.driver_invite_codes;
  v_driver public.drivers;
  v_token text;
begin
  select * into v_invite
    from public.driver_invite_codes
   where code = upper(trim(p_code))
     and consumed_at is null
     and expires_at > now();
  if v_invite.code is null then
    raise exception 'invalid_or_expired_code' using errcode = 'P0001';
  end if;

  select * into v_driver from public.drivers where id = v_invite.driver_id;
  if v_driver.id is null then
    raise exception 'driver_not_found' using errcode = 'P0002';
  end if;
  if v_driver.status not in ('active','onboarding') then
    raise exception 'driver_inactive' using errcode = 'P0001';
  end if;

  v_token := encode(gen_random_bytes(32), 'hex');

  insert into public.driver_sessions (token, dsp_id, driver_id, user_agent)
  values (v_token, v_invite.dsp_id, v_invite.driver_id, p_user_agent);

  update public.driver_invite_codes
     set consumed_at = now()
   where code = v_invite.code;

  return jsonb_build_object(
    'token', v_token,
    'driver', jsonb_build_object(
      'id',         v_driver.id,
      'dsp_id',     v_driver.dsp_id,
      'full_name',  v_driver.full_name,
      'name',       coalesce(nullif(trim(v_driver.preferred_name), ''), v_driver.full_name),
      'station_id', v_driver.station_id,
      'tier',       v_driver.tier
    )
  );
end;
$$;
grant execute on function public.redeem_driver_invite(text, text) to anon, authenticated;


-- ── 4. driver_validate_token — internal helper ──
-- Returns the driver row and updates last_seen_at. Raises if invalid.
create or replace function private.driver_validate_token(p_token text)
returns public.drivers
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_driver_id uuid;
  v_revoked timestamptz;
  v_drv public.drivers;
begin
  select driver_id, revoked_at into v_driver_id, v_revoked
    from public.driver_sessions where token = p_token;
  if v_driver_id is null then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  if v_revoked is not null then
    raise exception 'session_revoked' using errcode = '42501';
  end if;

  select * into v_drv from public.drivers where id = v_driver_id;
  if v_drv.status not in ('active','onboarding') then
    -- Auto-revoke when the driver becomes inactive.
    update public.driver_sessions set revoked_at = now() where token = p_token;
    raise exception 'driver_inactive' using errcode = '42501';
  end if;

  update public.driver_sessions
     set last_seen_at = now()
   where token = p_token;

  return v_drv;
end;
$$;


-- ── 5. driver_my_schedule — driver fetches their own shifts ──
create or replace function public.driver_my_schedule(p_token text, p_weeks int default 2)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_drv public.drivers;
  v_start date := private.week_start_for(current_date);
  v_end date;
  v_shifts jsonb;
begin
  v_drv := private.driver_validate_token(p_token);
  v_end := v_start + (greatest(1, least(8, coalesce(p_weeks, 2))) * 7) - 1;

  select coalesce(jsonb_agg(jsonb_build_object(
      'id',                sh.id,
      'date',              sh.date,
      'starts_at',         sh.starts_at,
      'ends_at',           sh.ends_at,
      'station_id',        sh.station_id,
      'station_code',      s.code,
      'status',            sh.status,
      'block_hours',       sh.block_hours,
      'wave_index',        sh.wave_index,
      'service_type_code', st.code,
      'service_type_color',st.color,
      'is_cushion',        sh.is_cushion,
      'route_code',        sh.route_code,
      'notes',             sh.notes
    ) order by sh.date, sh.starts_at), '[]'::jsonb)
    into v_shifts
  from public.shifts sh
  left join public.stations     s  on s.id  = sh.station_id
  left join public.service_types st on st.id = sh.service_type_id
  where sh.driver_id = v_drv.id
    and sh.date between v_start and v_end;

  return jsonb_build_object(
    'driver', jsonb_build_object(
      'id',        v_drv.id,
      'full_name', v_drv.full_name,
      'name',      coalesce(nullif(trim(v_drv.preferred_name), ''), v_drv.full_name)
    ),
    'shifts', v_shifts,
    'start',  v_start,
    'end',    v_end
  );
end;
$$;
grant execute on function public.driver_my_schedule(text, int) to anon, authenticated;


-- ── 6. driver_signout — explicit session revoke ──
create or replace function public.driver_signout(p_token text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.driver_sessions
     set revoked_at = now()
   where token = p_token and revoked_at is null;
end;
$$;
grant execute on function public.driver_signout(text) to anon, authenticated;
